/* Minimal CH32 register map owned by this core.
 *
 * This is an own implementation, not a copy of the WCH EVT headers: it defines
 * only the registers the core actually touches, uses plain offsets instead of
 * packed structs, and names things after the reference manual. Register
 * addresses are hardware facts; the EVT headers were read as a cross-check.
 *
 * Family differences are driven by build.core_defines (generated by
 * tools/generate/generate.py from the FAMILY table):
 *   CH32_GPIO_PORT_WIDTH   8 (V003/V00x), 16 (most), 24 (X033/X035)
 *   CH32_SYSTICK_64        1 when SysTick CNT/CMP are 64-bit
 *   CH32_I2C_HAS_RTR       1 when the I2C block has a rise-time register
 *   CH32_IRQNS             generated header naming each interrupt slot
 */
#pragma once

#include <stdint.h>

#ifndef CH32_GPIO_PORT_WIDTH
#error "CH32_GPIO_PORT_WIDTH is required (see build.core_defines in boards.txt)"
#endif
#ifndef CH32_SYSTICK_64
#error "CH32_SYSTICK_64 is required (see build.core_defines in boards.txt)"
#endif
#ifndef CH32_IRQNS
#error "CH32_IRQNS is required (see build.core_defines in boards.txt)"
#endif

#ifndef CH32_I2C_HAS_RTR
#error "CH32_I2C_HAS_RTR is required (see build.core_defines in boards.txt)"
#endif

#ifndef CH32_EXTIS
#error "CH32_EXTIS is required (see build.core_defines in boards.txt)"
#endif

#define CH32_STRINGIFY_(s) #s
#define CH32_GENERATED_(s) CH32_STRINGIFY_(s)
#include CH32_GENERATED_(CH32_IRQNS)
#include CH32_GENERATED_(CH32_EXTIS)

#define CH32_REG32(addr) (*(volatile uint32_t *)(uintptr_t)(addr))
#define CH32_REG16(addr) (*(volatile uint16_t *)(uintptr_t)(addr))
#define CH32_REG8(addr)  (*(volatile uint8_t  *)(uintptr_t)(addr))

/* ---------------------------------------------------------------- buses */
#define CH32_APB1_BASE 0x40000000u
#define CH32_APB2_BASE 0x40010000u
#define CH32_AHB_BASE  0x40020000u

/* ------------------------------------------------------------------ RCC */
#define CH32_RCC_BASE      (CH32_AHB_BASE + 0x1000u)
#define CH32_RCC_CTLR      CH32_REG32(CH32_RCC_BASE + 0x00u)
#define CH32_RCC_CFGR0     CH32_REG32(CH32_RCC_BASE + 0x04u)
#define CH32_RCC_AHBPCENR  CH32_REG32(CH32_RCC_BASE + 0x14u)
#define CH32_RCC_APB2PCENR CH32_REG32(CH32_RCC_BASE + 0x18u)
#define CH32_RCC_APB1PCENR CH32_REG32(CH32_RCC_BASE + 0x1Cu)

#define CH32_RCC_CTLR_HSION  (1u << 0)
#define CH32_RCC_CTLR_HSIRDY (1u << 1)
/* Same on every family clock_symbols.csv covers (10 for PLLON/PLLRDY, 11 for
 * the SW fields below), which is why these are here and the PLL *value* is
 * not. */
#define CH32_RCC_CTLR_PLLON  (1u << 24)
#define CH32_RCC_CTLR_PLLRDY (1u << 25)

#define CH32_RCC_CFGR0_SW_MASK   0x3u        /* system clock switch          */
#define CH32_RCC_CFGR0_SW_HSI    0x0u
#define CH32_RCC_CFGR0_SW_PLL    0x2u
/* The fields the PLL configuration occupies are NOT the same everywhere, so
 * the mask to clear comes from boards.txt (CH32_CLOCK_PLL_MASK) rather than
 * from here: PLLMULL is four bits at 0x003C0000 on CH32V103/V20x/V30x/L103,
 * five bits at 0x007C0000 on CH32V205 and at 0x003E0000 on CH32V407, and
 * CH32X315 uses different fields entirely. CH32V307 additionally has PLL2MUL
 * and PLL3MUL in the same register, which must not be cleared along with it.
 */
#define CH32_RCC_CFGR0_SWS_MASK  (0x3u << 2) /* switch status (read-back)    */
#define CH32_RCC_CFGR0_HPRE_MASK (0xFu << 4) /* AHB prescaler                */
/* The field value itself, not the divider: the CH32 line encodes AHB dividers
 * two different ways and only wiring_time.c knows which one this build needs.
 * See CH32_HPRE_LINEAR there. */
#define CH32_RCC_CFGR0_HPRE(n)   ((uint32_t)(n) << 4)
#define CH32_RCC_CFGR0_PPRE1_MASK (0x7u << 8)
#define CH32_RCC_CFGR0_PPRE2_MASK (0x7u << 11)

/* APB2 peripheral clock enables (bit positions are uniform across CH32). */
/* Peripheral clock enables are NOT spelled out here. The register and bit
 * differ per family - CH32V006 has USART2 on the APB2 register at bit 13
 * where the F1-style parts have it on APB1 bit 17, and its TIM3 is bit 2 not
 * bit 1 - and two of the hand-written constants that used to live here were
 * exactly those two, wrong for that whole family and never caught because no
 * V00x board was on the bench. The variant header now carries
 *
 *     CH32_CLKEN_<PERIPHERAL>_ADDR / _MASK      (generated from clock_enables.csv)
 *
 * for every block the family has, plus CH32_CLKEN_GPIO_ADDR/_BIT0 for the
 * ports, and the helpers below use them. */
#define CH32_CLKEN_(name, op) \
    (CH32_REG32(CH32_CLKEN_##name##_ADDR) op CH32_CLKEN_##name##_MASK)
#define ch32_clock_enable(name)  CH32_CLKEN_(name, |=)
#define ch32_clock_disable(name) CH32_CLKEN_(name, &= ~)
static inline void ch32_clock_enable_at(uint32_t addr, uint32_t mask)
{
    CH32_REG32(addr) |= mask;
}
static inline void ch32_clock_disable_at(uint32_t addr, uint32_t mask)
{
    CH32_REG32(addr) &= ~mask;
}
/* APB1 */

/* ------------------------------------------------------------------ I2C */
/* Both instances sit on APB1. Families with one I2C simply have no I2C2 pins,
 * so nothing names the second base. The registers are 16-bit and every one is
 * padded to a 32-bit slot, which is why the offsets step by four. */
#define CH32_I2C1_BASE (CH32_APB1_BASE + 0x5400u)
#define CH32_I2C2_BASE (CH32_APB1_BASE + 0x5800u)

#define CH32_I2C_CTLR1(b)  CH32_REG16((b) + 0x00u)
#define CH32_I2C_CTLR2(b)  CH32_REG16((b) + 0x04u)
#define CH32_I2C_OADDR1(b) CH32_REG16((b) + 0x08u)
#define CH32_I2C_OADDR2(b) CH32_REG16((b) + 0x0Cu)
#define CH32_I2C_DATAR(b)  CH32_REG16((b) + 0x10u)
#define CH32_I2C_STAR1(b)  CH32_REG16((b) + 0x14u)
#define CH32_I2C_STAR2(b)  CH32_REG16((b) + 0x18u)
#define CH32_I2C_CKCFGR(b) CH32_REG16((b) + 0x1Cu)
/* Rise-time register. V003/V00x/X03x/M030 have no such register - their I2C
 * block ends at CKCFGR - so it is only written where CH32_I2C_HAS_RTR says so
 * (build.core_defines, from the FAMILY table in generate.py). */
#define CH32_I2C_RTR(b)    CH32_REG16((b) + 0x20u)

#define CH32_I2C_CTLR1_PE      (1u << 0)   /* peripheral enable             */
#define CH32_I2C_CTLR1_START   (1u << 8)
#define CH32_I2C_CTLR1_STOP    (1u << 9)
#define CH32_I2C_CTLR1_ACK     (1u << 10)
#define CH32_I2C_CTLR1_POS     (1u << 11)  /* ACK applies to the next byte  */
#define CH32_I2C_CTLR1_SWRST   (1u << 15)

#define CH32_I2C_CTLR2_FREQ_MASK 0x3Fu     /* APB1 clock in MHz             */
#define CH32_I2C_CTLR2_ITERREN  (1u << 8)  /* error interrupt enable        */
#define CH32_I2C_CTLR2_ITEVTEN  (1u << 9)  /* event interrupt enable        */
#define CH32_I2C_CTLR2_ITBUFEN  (1u << 10) /* TXE/RXNE raise the event IRQ  */

#define CH32_I2C_STAR1_SB      (1u << 0)   /* start condition generated     */
#define CH32_I2C_STAR1_ADDR    (1u << 1)   /* address sent / matched        */
#define CH32_I2C_STAR1_BTF     (1u << 2)   /* byte transfer finished        */
#define CH32_I2C_STAR1_STOPF   (1u << 4)   /* stop received (slave)         */
#define CH32_I2C_STAR1_RXNE    (1u << 6)
#define CH32_I2C_STAR1_TXE     (1u << 7)
#define CH32_I2C_STAR1_BERR    (1u << 8)
#define CH32_I2C_STAR1_ARLO    (1u << 9)   /* arbitration lost              */
#define CH32_I2C_STAR1_AF      (1u << 10)  /* acknowledge failure = NACK    */
#define CH32_I2C_STAR1_OVR     (1u << 11)

#define CH32_I2C_STAR2_MSL     (1u << 0)   /* master mode                   */
#define CH32_I2C_STAR2_BUSY    (1u << 1)
#define CH32_I2C_STAR2_TRA     (1u << 2)   /* transmitting                  */

#define CH32_I2C_CKCFGR_CCR_MASK 0x0FFFu
#define CH32_I2C_CKCFGR_DUTY     (1u << 14) /* fast mode 16/9 instead of 2/1 */
#define CH32_I2C_CKCFGR_FS       (1u << 15) /* fast mode                     */

/* APB1 */

/* ------------------------------------------------------------------ SPI */
/* SPI1 is on APB2, SPI2/SPI3 on APB1. Like the I2C block the registers are
 * 16-bit in 32-bit slots. Only what a master transfer needs is named; the CRC
 * and I2S registers are left out. */
#define CH32_SPI1_BASE (CH32_APB2_BASE + 0x3000u)
#define CH32_SPI2_BASE (CH32_APB1_BASE + 0x3800u)
#define CH32_SPI3_BASE (CH32_APB1_BASE + 0x3C00u)

#define CH32_SPI_CTLR1(b) CH32_REG16((b) + 0x00u)
#define CH32_SPI_CTLR2(b) CH32_REG16((b) + 0x04u)
#define CH32_SPI_STATR(b) CH32_REG16((b) + 0x08u)
#define CH32_SPI_DATAR(b) CH32_REG16((b) + 0x0Cu)

#define CH32_SPI_CTLR1_CPHA      (1u << 0)
#define CH32_SPI_CTLR1_CPOL      (1u << 1)
#define CH32_SPI_CTLR1_MSTR      (1u << 2)
#define CH32_SPI_CTLR1_BR_SHIFT  3          /* divider = 2^(BR+1)            */
#define CH32_SPI_CTLR1_BR_MASK   (0x7u << 3)
#define CH32_SPI_CTLR1_SPE       (1u << 6)
#define CH32_SPI_CTLR1_LSBFIRST  (1u << 7)
#define CH32_SPI_CTLR1_SSI       (1u << 8)  /* the value NSS reads as        */
#define CH32_SPI_CTLR1_SSM       (1u << 9)  /* NSS from SSI, not from a pin  */
#define CH32_SPI_CTLR1_RXONLY    (1u << 10)
#define CH32_SPI_CTLR1_DFF       (1u << 11) /* 16-bit frames                 */
#define CH32_SPI_CTLR1_BIDIOE    (1u << 14)
#define CH32_SPI_CTLR1_BIDIMODE  (1u << 15)

#define CH32_SPI_STATR_RXNE      (1u << 0)
#define CH32_SPI_STATR_TXE       (1u << 1)
#define CH32_SPI_STATR_MODF      (1u << 5)
#define CH32_SPI_STATR_OVR       (1u << 6)
#define CH32_SPI_STATR_BSY       (1u << 7)

/* APB1 */

/* ------------------------------------------------------------------ DAC */
/* Only V303/V305/V307/V4x7 have one. The variant names the pads it reaches
 * (CH32_DACn_PIN); nothing here is referenced otherwise. */
#define CH32_DAC_BASE (CH32_APB1_BASE + 0x7400u)
#define CH32_DAC_CTLR      CH32_REG32(CH32_DAC_BASE + 0x00u)
#define CH32_DAC_R12BDHR1  CH32_REG32(CH32_DAC_BASE + 0x08u)
#define CH32_DAC_R12BDHR2  CH32_REG32(CH32_DAC_BASE + 0x14u)

#define CH32_DAC_CTLR_EN1   (1u << 0)
#define CH32_DAC_CTLR_BOFF1 (1u << 1)   /* 1 disables the output buffer */
#define CH32_DAC_CTLR_EN2   (1u << 16)
#define CH32_DAC_CTLR_BOFF2 (1u << 17)


/* ---------------------------------------------------------------- FLASH */
/* Flash controller registers (not the flash memory itself). */
#define CH32_FLASH_BASE  (CH32_AHB_BASE + 0x2000u)
#define CH32_FLASH_ACTLR CH32_REG32(CH32_FLASH_BASE + 0x00u)
/* The LATENCY field is not the same width everywhere: CH32V003/V006/V103/
 * L103/X035 have two bits, CH32M030 three, CH32V205 four - and CH32V20x,
 * CH32V307 and CH32V407 have no wait states at all, where the mask is 0 and
 * the field must be left alone rather than written with a harmless-looking 0.
 * boards.txt carries the family's own value, read out of clock_symbols.csv. */
#ifndef CH32_FLASH_ACTLR_LATENCY_MASK
#error "CH32_FLASH_ACTLR_LATENCY_MASK is required (see build.core_defines)"
#endif

/* ----------------------------------------------------------------- AFIO */
#define CH32_AFIO_BASE  (CH32_APB2_BASE + 0x0000u)
#define CH32_AFIO_ECR   CH32_REG32(CH32_AFIO_BASE + 0x00u)
#define CH32_AFIO_PCFR1 CH32_REG32(CH32_AFIO_BASE + 0x04u)  /* peripheral remap */
#define CH32_AFIO_PCFR2 CH32_REG32(CH32_AFIO_BASE + 0x1Cu)

/* ----------------------------------------------------------------- GPIO */
/* Ports are 0x400 apart starting at PA, whether or not the port exists. */
#define CH32_GPIO_BASE(port) (CH32_APB2_BASE + 0x0800u + 0x400u * (uint32_t)(port))
#define CH32_GPIO_CFGLR(p)   CH32_REG32(CH32_GPIO_BASE(p) + 0x00u)
#define CH32_GPIO_CFGHR(p)   CH32_REG32(CH32_GPIO_BASE(p) + 0x04u)
#define CH32_GPIO_INDR(p)    CH32_REG32(CH32_GPIO_BASE(p) + 0x08u)
#define CH32_GPIO_OUTDR(p)   CH32_REG32(CH32_GPIO_BASE(p) + 0x0Cu)
#define CH32_GPIO_BSHR(p)    CH32_REG32(CH32_GPIO_BASE(p) + 0x10u)
#define CH32_GPIO_BCR(p)     CH32_REG32(CH32_GPIO_BASE(p) + 0x14u)
#define CH32_GPIO_LCKR(p)    CH32_REG32(CH32_GPIO_BASE(p) + 0x18u)
/* 24-pin ports (X033/X035) only: config and set for bits 16..23. */
#define CH32_GPIO_CFGXR(p)   CH32_REG32(CH32_GPIO_BASE(p) + 0x1Cu)
#define CH32_GPIO_BSXR(p)    CH32_REG32(CH32_GPIO_BASE(p) + 0x20u)

/* Pin configuration nibble: (CNF << 2) | MODE, four bits per pin. */
#define CH32_GPIO_CFG_IN_ANALOG   0x0u
#define CH32_GPIO_CFG_IN_FLOAT    0x4u
#define CH32_GPIO_CFG_IN_PULL     0x8u  /* OUTDR bit picks up (1) or down (0) */
#define CH32_GPIO_CFG_OUT_PP_10M  0x1u
#define CH32_GPIO_CFG_OUT_OD_10M  0x5u
#define CH32_GPIO_CFG_AF_PP_50M   0xBu
#define CH32_GPIO_CFG_AF_OD_50M   0xFu

/* ---------------------------------------------------------------- USART */
#define CH32_USART1_BASE (CH32_APB2_BASE + 0x3800u)
#define CH32_USART2_BASE (CH32_APB1_BASE + 0x4400u)
#define CH32_USART3_BASE (CH32_APB1_BASE + 0x4800u)
#define CH32_USART4_BASE (CH32_APB1_BASE + 0x4C00u)   /* UART4 */
#define CH32_USART5_BASE (CH32_APB1_BASE + 0x5000u)   /* UART5 */

#define CH32_USART_STATR(b) CH32_REG16((b) + 0x00u)
#define CH32_USART_DATAR(b) CH32_REG16((b) + 0x04u)
#define CH32_USART_BRR(b)   CH32_REG16((b) + 0x08u)
#define CH32_USART_CTLR1(b) CH32_REG16((b) + 0x0Cu)
#define CH32_USART_CTLR2(b) CH32_REG16((b) + 0x10u)
#define CH32_USART_CTLR3(b) CH32_REG16((b) + 0x14u)

#define CH32_USART_STATR_PE   (1u << 0)
#define CH32_USART_STATR_FE   (1u << 1)
#define CH32_USART_STATR_NE   (1u << 2)
#define CH32_USART_STATR_ORE  (1u << 3)
#define CH32_USART_STATR_IDLE (1u << 4)
#define CH32_USART_STATR_RXNE (1u << 5)
#define CH32_USART_STATR_TC   (1u << 6)
#define CH32_USART_STATR_TXE  (1u << 7)

#define CH32_USART_CTLR1_RE     (1u << 2)
#define CH32_USART_CTLR1_TE     (1u << 3)
#define CH32_USART_CTLR1_RXNEIE (1u << 5)
#define CH32_USART_CTLR1_TXEIE  (1u << 7)
#define CH32_USART_CTLR1_PCE    (1u << 10)
#define CH32_USART_CTLR1_PS     (1u << 9)
#define CH32_USART_CTLR1_M      (1u << 12)
#define CH32_USART_CTLR1_UE     (1u << 13)

#define CH32_USART_CTLR2_STOP_1   (0u << 12)
#define CH32_USART_CTLR2_STOP_0P5 (1u << 12)
#define CH32_USART_CTLR2_STOP_2   (2u << 12)
#define CH32_USART_CTLR2_STOP_1P5 (3u << 12)

/* -------------------------------------------------------------- SysTick */
/* CH32V103 (QingKe V3A) lays this out differently from every other family:
 * there is no status register, the counter starts where SR is elsewhere, the
 * compare sits four bytes lower, CTLR has no interrupt-enable or clock-select
 * bit, and the source is fixed at HCLK/8. Confirmed against WCH's own
 * core_riscv.h, EVT's SYSTICK/SYSTICK_Interrupt example, and measured on a
 * CH32V103R8T6 - writing the compare at the other families' offset put it in
 * the high word, so the match never happened and millis() never advanced. */
#ifndef CH32_SYSTICK_V103
#error "CH32_SYSTICK_V103 is required (see build.core_defines in boards.txt)"
#endif

#define CH32_SYSTICK_BASE 0xE000F000u
#define CH32_SYSTICK_CTLR CH32_REG32(CH32_SYSTICK_BASE + 0x00u)
#if CH32_SYSTICK_V103
/* Read as a word - EVT's own delay loop does - but WRITE AS BYTES. WCH
 * declares these as four uint8_t each and every EVT example writes them one
 * byte at a time; a word write is ignored. Measured: after a word write the
 * counter carried on past the compare, matched once on the way up and never
 * again, so millis() stopped at 1. */
#define CH32_SYSTICK_CNT    CH32_REG32(CH32_SYSTICK_BASE + 0x04u)
#define CH32_SYSTICK_CNT_HI CH32_REG32(CH32_SYSTICK_BASE + 0x08u)
#define CH32_SYSTICK_CMP    CH32_REG32(CH32_SYSTICK_BASE + 0x0Cu)
#define CH32_SYSTICK_CMP_HI CH32_REG32(CH32_SYSTICK_BASE + 0x10u)
#define CH32_SYSTICK_WRITE8(off, v) do { \
    CH32_REG8(CH32_SYSTICK_BASE + (off) + 0u) = (uint8_t)((v) >> 0);  \
    CH32_REG8(CH32_SYSTICK_BASE + (off) + 1u) = (uint8_t)((v) >> 8);  \
    CH32_REG8(CH32_SYSTICK_BASE + (off) + 2u) = (uint8_t)((v) >> 16); \
    CH32_REG8(CH32_SYSTICK_BASE + (off) + 3u) = (uint8_t)((v) >> 24); \
} while (0)
#else
#define CH32_SYSTICK_SR   CH32_REG32(CH32_SYSTICK_BASE + 0x04u)
#define CH32_SYSTICK_CNT  CH32_REG32(CH32_SYSTICK_BASE + 0x08u)  /* low word */
#define CH32_SYSTICK_CMP  CH32_REG32(CH32_SYSTICK_BASE + 0x10u)  /* low word */
#if CH32_SYSTICK_64
#define CH32_SYSTICK_CNT_HI CH32_REG32(CH32_SYSTICK_BASE + 0x0Cu)
#define CH32_SYSTICK_CMP_HI CH32_REG32(CH32_SYSTICK_BASE + 0x14u)
#endif
#endif

#define CH32_SYSTICK_CTLR_STE   (1u << 0)  /* counter enable                 */
#define CH32_SYSTICK_CTLR_STIE  (1u << 1)  /* interrupt enable               */
#define CH32_SYSTICK_CTLR_STCLK (1u << 2)  /* 1 = HCLK, 0 = HCLK/8           */

/* ------------------------------------------------------- PFIC (like NVIC) */
#define CH32_PFIC_BASE    0xE000E000u
#define CH32_PFIC_IENR(i) CH32_REG32(CH32_PFIC_BASE + 0x100u + 4u * (i))
#define CH32_PFIC_IRER(i) CH32_REG32(CH32_PFIC_BASE + 0x180u + 4u * (i))
#define CH32_PFIC_IPRIOR(n) CH32_REG8(CH32_PFIC_BASE + 0x400u + (n))

static inline void ch32_irq_enable(uint32_t irqn)
{
    CH32_PFIC_IENR(irqn >> 5) = 1u << (irqn & 31u);
}

static inline void ch32_irq_disable(uint32_t irqn)
{
    CH32_PFIC_IRER(irqn >> 5) = 1u << (irqn & 31u);
}

/* System reset through the PFIC, the RISC-V equivalent of NVIC_SystemReset:
 * the config register takes a key in the top half and the reset request in
 * bit 7. Identical across every EVT's core_riscv.h. */
#define CH32_PFIC_CFGR    CH32_REG32(CH32_PFIC_BASE + 0x48u)
#define CH32_PFIC_KEY3    0xBEEF0000u
#define CH32_PFIC_SYSRST  (1u << 7)

/* ---------------------------------------------------------- reset cause */
/* RSTSCKR sits at RCC+0x24 with the same flag bits on every family checked
 * (V003/V00x/V103/L103/X035/V307/M030); some families add flags in lower
 * bits, which readers should ignore rather than misname. The flags survive
 * everything except a write of RMVF, so they describe the *oldest* unread
 * reset, not necessarily the latest. */
#define CH32_RCC_RSTSCKR  CH32_REG32(CH32_RCC_BASE + 0x24u)
#define CH32_RST_RMVF     (1u << 24)   /* write 1 to clear all flags */
#define CH32_RST_PIN      (1u << 26)   /* NRST pin                    */
#define CH32_RST_POR      (1u << 27)   /* power on                    */
#define CH32_RST_SFT      (1u << 28)   /* software (CH32_PFIC_SYSRST) */
#define CH32_RST_IWDG     (1u << 29)
#define CH32_RST_WWDG     (1u << 30)
#define CH32_RST_LPWR     (1u << 31)

/* ----------------------------------------------------------------- IWDG */
/* The independent watchdog: LSI-clocked, and irreversible by design - once
 * the 0xCCCC key starts it, only a reset stops it. Registers and keys are
 * the F1-classic layout on every family that has the block; CH32_IWDG_BASE
 * itself comes from build.core_defines, generated from memory_map.csv, so a
 * family without the block (CH32M030) simply has no base and no watchdog
 * API. */
#define CH32_IWDG_CTLR    CH32_REG16(CH32_IWDG_BASE + 0x00u)  /* key register */
#define CH32_IWDG_PSCR    CH32_REG16(CH32_IWDG_BASE + 0x04u)  /* prescaler   */
#define CH32_IWDG_RLDR    CH32_REG16(CH32_IWDG_BASE + 0x08u)  /* reload      */
#define CH32_IWDG_STATR   CH32_REG16(CH32_IWDG_BASE + 0x0Cu)  /* update busy */
#define CH32_IWDG_KEY_UNLOCK 0x5555u   /* PSCR/RLDR become writable  */
#define CH32_IWDG_KEY_FEED   0xAAAAu
#define CH32_IWDG_KEY_START  0xCCCCu

/* ------------------------------------------------------------------ ADC */
/* Layout is the same on every family the platform builds for - checked
 * against index/registers.csv for all twelve, CH32X315 included - so only the
 * base address changes between instances, and only the conversion width
 * changes between families (CH32_ADC_BITS, from build.core_defines).
 *
 * The _AT(base) forms exist for CH32X305/CH32X315, whose four ADCs sit on
 * disjoint pads: there, a pad names an instance as well as a channel, and the
 * variant maps it (CH32_PIN_TO_ADC_INSTANCE). Everywhere else the base folds
 * to the ADC1 constant and the generated code is unchanged. */
#define CH32_ADC1_BASE   (CH32_APB2_BASE + 0x2400u)
#define CH32_ADC_STATR_AT(base)   CH32_REG32((base) + 0x00u)
#define CH32_ADC_CTLR1_AT(base)   CH32_REG32((base) + 0x04u)
#define CH32_ADC_CTLR2_AT(base)   CH32_REG32((base) + 0x08u)
#define CH32_ADC_SAMPTR1_AT(base) CH32_REG32((base) + 0x0Cu) /* channels 10..17 */
#define CH32_ADC_SAMPTR2_AT(base) CH32_REG32((base) + 0x10u) /* channels 0..9   */
#define CH32_ADC_RSQR1_AT(base)   CH32_REG32((base) + 0x2Cu)
#define CH32_ADC_RSQR3_AT(base)   CH32_REG32((base) + 0x34u)
#define CH32_ADC_RDATAR_AT(base)  CH32_REG32((base) + 0x4Cu)

#define CH32_ADC_STATR   CH32_ADC_STATR_AT(CH32_ADC1_BASE)
#define CH32_ADC_CTLR1   CH32_ADC_CTLR1_AT(CH32_ADC1_BASE)
#define CH32_ADC_CTLR2   CH32_ADC_CTLR2_AT(CH32_ADC1_BASE)
#define CH32_ADC_SAMPTR1 CH32_ADC_SAMPTR1_AT(CH32_ADC1_BASE)
#define CH32_ADC_SAMPTR2 CH32_ADC_SAMPTR2_AT(CH32_ADC1_BASE)
#define CH32_ADC_RSQR1   CH32_ADC_RSQR1_AT(CH32_ADC1_BASE)
#define CH32_ADC_RSQR3   CH32_ADC_RSQR3_AT(CH32_ADC1_BASE)
#define CH32_ADC_RDATAR  CH32_ADC_RDATAR_AT(CH32_ADC1_BASE)

#define CH32_ADC_STATR_EOC   (1u << 1)
#define CH32_ADC_CTLR2_ADON    (1u << 0)
#define CH32_ADC_CTLR2_CAL     (1u << 2)
#define CH32_ADC_CTLR2_RSTCAL  (1u << 3)
#define CH32_ADC_CTLR2_EXTSEL_SWSTART (7u << 17)
#define CH32_ADC_CTLR2_EXTTRIG (1u << 20)
#define CH32_ADC_CTLR2_SWSTART (1u << 22)
/* RCC_CFGR0 ADCPRE: 00=/2 01=/4 10=/6 11=/8. ADCCLK must stay under 14 MHz. */
#define CH32_RCC_CFGR0_ADCPRE_MASK (0x3u << 14)
#define CH32_RCC_CFGR0_ADCPRE(n)   ((uint32_t)(n) << 14)

/* ----------------------------------------------------------------- EXTI */
#define CH32_EXTI_BASE   (CH32_APB2_BASE + 0x0400u)
#define CH32_EXTI_INTENR CH32_REG32(CH32_EXTI_BASE + 0x00u)
#define CH32_EXTI_EVENR  CH32_REG32(CH32_EXTI_BASE + 0x04u)
#define CH32_EXTI_RTENR  CH32_REG32(CH32_EXTI_BASE + 0x08u)
#define CH32_EXTI_FTENR  CH32_REG32(CH32_EXTI_BASE + 0x0Cu)
#define CH32_EXTI_SWIEVR CH32_REG32(CH32_EXTI_BASE + 0x10u)
#define CH32_EXTI_INTFR  CH32_REG32(CH32_EXTI_BASE + 0x14u)
/* Which port drives EXTI line n: four lines per word, four bits each. */
#define CH32_AFIO_EXTICR(n) CH32_REG32(CH32_AFIO_BASE + 0x08u + 4u * (n))

/* ---------------------------------------------------------------- timers */
/* TIM1 is the advanced timer on APB2; TIM2/TIM3 are general purpose on APB1.
 * The register block is the same for all of them. */
#define CH32_TIM1_BASE (CH32_APB2_BASE + 0x2C00u)
#define CH32_TIM2_BASE (CH32_APB1_BASE + 0x0000u)
#define CH32_TIM3_BASE (CH32_APB1_BASE + 0x0400u)
/* Only some families have these. Which one tone() uses is decided by the
 * generator and named by CH32_TONE_TIMER in the variant. */
#define CH32_TIM4_BASE (CH32_APB1_BASE + 0x0800u)
#define CH32_TIM5_BASE (CH32_APB1_BASE + 0x0C00u)
#define CH32_TIM6_BASE (CH32_APB1_BASE + 0x1000u)
#define CH32_TIM7_BASE (CH32_APB1_BASE + 0x1400u)

#define CH32_TIM_CTLR1(b)   CH32_REG16((b) + 0x00u)
#define CH32_TIM_DMAINTENR(b) CH32_REG16((b) + 0x0Cu) /* interrupt enables */
#define CH32_TIM_INTFR(b)   CH32_REG16((b) + 0x10u)   /* interrupt flags   */
#define CH32_TIM_SWEVGR(b)  CH32_REG16((b) + 0x14u)   /* software events   */
#define CH32_TIM_CHCTLR1(b) CH32_REG16((b) + 0x18u)   /* channels 1 and 2 */
#define CH32_TIM_CHCTLR2(b) CH32_REG16((b) + 0x1Cu)   /* channels 3 and 4 */
#define CH32_TIM_CCER(b)    CH32_REG16((b) + 0x20u)
#define CH32_TIM_CNT(b)     CH32_REG16((b) + 0x24u)
#define CH32_TIM_PSC(b)     CH32_REG16((b) + 0x28u)
#define CH32_TIM_ATRLR(b)   CH32_REG16((b) + 0x2Cu)   /* auto-reload */
#define CH32_TIM_CHCVR(b, ch) CH32_REG16((b) + 0x34u + 4u * ((ch) - 1u))

/* Some families have one 32-bit timer, and on it CNT, ATRLR and CHnCVR are a
 * single 32-bit register rather than a 16-bit one with a reserved upper half.
 * A 16-bit store to such a register is *replicated into both halves* by the
 * bus: writing 7999 (0x1F3F) to ATRLR leaves 0x1F3F1F3F, so the counter runs
 * for a minute instead of a millisecond and the update event never arrives.
 *
 * Measured on CH32L103's TIM4 on 2026-08-25, which is what made tone() silent
 * there. EVT's own header says the same, with a union: ch32l103.h has
 * ATRLR_TIM4/CNT_TIM4 beside the 16-bit ATRLR/CNT.
 *
 * The variant says which timer is wide, as CH32_<user>_TIMER_BITS. */
#define CH32_TIM_CNT32(b)   CH32_REG32((b) + 0x24u)
#define CH32_TIM_ATRLR32(b) CH32_REG32((b) + 0x2Cu)
#define CH32_TIM_CHCVR32(b, ch) CH32_REG32((b) + 0x34u + 4u * ((ch) - 1u))
#define CH32_TIM_BDTR(b)    CH32_REG16((b) + 0x44u)   /* TIM1 only */

#define CH32_TIM_CTLR1_CEN  (1u << 0)
#define CH32_TIM_CTLR1_ARPE (1u << 7)
#define CH32_TIM_INT_UIE    (1u << 0)  /* update interrupt enable / flag */
#define CH32_TIM_SWEVGR_UG  (1u << 0)  /* force an update event          */
#define CH32_TIM_BDTR_MOE   (1u << 15)
/* PWM mode 1 with preload, in the low or high half of a CHCTLR word. */
#define CH32_TIM_OCMODE_PWM1 0x68u

