/* Minimal CH32 register map owned by this core.
 *
 * This is an own implementation, not a copy of the WCH EVT headers: it defines
 * only the registers the core actually touches, uses plain offsets instead of
 * packed structs, and names things after the reference manual. Register
 * addresses are hardware facts; the EVT headers were read as a cross-check.
 *
 * Family differences are driven by build.core_defines (generated by
 * tools/generate/generate.py from the FAMILY table):
 *   CH32_GPIO_PORT_WIDTH   8 (V003/V00x), 16 (most), 24 (X033/X035)
 *   CH32_SYSTICK_64        1 when SysTick CNT/CMP are 64-bit
 *   CH32_I2C_HAS_RTR       1 when the I2C block has a rise-time register
 *   CH32_IRQNS             generated header naming each interrupt slot
 */
#pragma once

#include <stdint.h>

#ifndef CH32_GPIO_PORT_WIDTH
#error "CH32_GPIO_PORT_WIDTH is required (see build.core_defines in boards.txt)"
#endif
#ifndef CH32_SYSTICK_64
#error "CH32_SYSTICK_64 is required (see build.core_defines in boards.txt)"
#endif
#ifndef CH32_IRQNS
#error "CH32_IRQNS is required (see build.core_defines in boards.txt)"
#endif

#ifndef CH32_I2C_HAS_RTR
#error "CH32_I2C_HAS_RTR is required (see build.core_defines in boards.txt)"
#endif

#ifndef CH32_EXTIS
#error "CH32_EXTIS is required (see build.core_defines in boards.txt)"
#endif

#define CH32_STRINGIFY_(s) #s
#define CH32_GENERATED_(s) CH32_STRINGIFY_(s)
#include CH32_GENERATED_(CH32_IRQNS)
#include CH32_GENERATED_(CH32_EXTIS)

#define CH32_REG32(addr) (*(volatile uint32_t *)(uintptr_t)(addr))
#define CH32_REG16(addr) (*(volatile uint16_t *)(uintptr_t)(addr))
#define CH32_REG8(addr)  (*(volatile uint8_t  *)(uintptr_t)(addr))

/* ---------------------------------------------------------------- buses */
#define CH32_APB1_BASE 0x40000000u
#define CH32_APB2_BASE 0x40010000u
#define CH32_AHB_BASE  0x40020000u

/* ------------------------------------------------------------------ RCC */
#define CH32_RCC_BASE      (CH32_AHB_BASE + 0x1000u)
#define CH32_RCC_CTLR      CH32_REG32(CH32_RCC_BASE + 0x00u)
#define CH32_RCC_CFGR0     CH32_REG32(CH32_RCC_BASE + 0x04u)
#define CH32_RCC_APB2PCENR CH32_REG32(CH32_RCC_BASE + 0x18u)
#define CH32_RCC_APB1PCENR CH32_REG32(CH32_RCC_BASE + 0x1Cu)

#define CH32_RCC_CTLR_HSION  (1u << 0)
#define CH32_RCC_CTLR_HSIRDY (1u << 1)

#define CH32_RCC_CFGR0_SW_MASK   0x3u        /* system clock switch          */
#define CH32_RCC_CFGR0_SW_HSI    0x0u
#define CH32_RCC_CFGR0_SWS_MASK  (0x3u << 2) /* switch status (read-back)    */
#define CH32_RCC_CFGR0_HPRE_MASK (0xFu << 4) /* AHB prescaler                */
/* The field value itself, not the divider: the CH32 line encodes AHB dividers
 * two different ways and only wiring_time.c knows which one this build needs.
 * See CH32_HPRE_LINEAR there. */
#define CH32_RCC_CFGR0_HPRE(n)   ((uint32_t)(n) << 4)
#define CH32_RCC_CFGR0_PPRE1_MASK (0x7u << 8)
#define CH32_RCC_CFGR0_PPRE2_MASK (0x7u << 11)

/* APB2 peripheral clock enables (bit positions are uniform across CH32). */
#define CH32_RCC_APB2_AFIO   (1u << 0)
#define CH32_RCC_APB2_IOP(p) (1u << (2 + (p)))   /* p: 0=PA, 1=PB, ...        */
#define CH32_RCC_APB2_ADC1   (1u << 9)
#define CH32_RCC_APB2_TIM1   (1u << 11)
#define CH32_RCC_APB2_SPI1   (1u << 12)
#define CH32_RCC_APB2_USART1 (1u << 14)
/* APB1 */
#define CH32_RCC_APB1_USART2 (1u << 17)
#define CH32_RCC_APB1_USART3 (1u << 18)
#define CH32_RCC_APB1_USART4 (1u << 19)
#define CH32_RCC_APB1_USART5 (1u << 20)

/* ------------------------------------------------------------------ I2C */
/* Both instances sit on APB1. Families with one I2C simply have no I2C2 pins,
 * so nothing names the second base. The registers are 16-bit and every one is
 * padded to a 32-bit slot, which is why the offsets step by four. */
#define CH32_I2C1_BASE (CH32_APB1_BASE + 0x5400u)
#define CH32_I2C2_BASE (CH32_APB1_BASE + 0x5800u)

#define CH32_I2C_CTLR1(b)  CH32_REG16((b) + 0x00u)
#define CH32_I2C_CTLR2(b)  CH32_REG16((b) + 0x04u)
#define CH32_I2C_OADDR1(b) CH32_REG16((b) + 0x08u)
#define CH32_I2C_OADDR2(b) CH32_REG16((b) + 0x0Cu)
#define CH32_I2C_DATAR(b)  CH32_REG16((b) + 0x10u)
#define CH32_I2C_STAR1(b)  CH32_REG16((b) + 0x14u)
#define CH32_I2C_STAR2(b)  CH32_REG16((b) + 0x18u)
#define CH32_I2C_CKCFGR(b) CH32_REG16((b) + 0x1Cu)
/* Rise-time register. V003/V00x/X03x/M030 have no such register - their I2C
 * block ends at CKCFGR - so it is only written where CH32_I2C_HAS_RTR says so
 * (build.core_defines, from the FAMILY table in generate.py). */
#define CH32_I2C_RTR(b)    CH32_REG16((b) + 0x20u)

#define CH32_I2C_CTLR1_PE      (1u << 0)   /* peripheral enable             */
#define CH32_I2C_CTLR1_START   (1u << 8)
#define CH32_I2C_CTLR1_STOP    (1u << 9)
#define CH32_I2C_CTLR1_ACK     (1u << 10)
#define CH32_I2C_CTLR1_POS     (1u << 11)  /* ACK applies to the next byte  */
#define CH32_I2C_CTLR1_SWRST   (1u << 15)

#define CH32_I2C_CTLR2_FREQ_MASK 0x3Fu     /* APB1 clock in MHz             */

#define CH32_I2C_STAR1_SB      (1u << 0)   /* start condition generated     */
#define CH32_I2C_STAR1_ADDR    (1u << 1)   /* address sent / matched        */
#define CH32_I2C_STAR1_BTF     (1u << 2)   /* byte transfer finished        */
#define CH32_I2C_STAR1_RXNE    (1u << 6)
#define CH32_I2C_STAR1_TXE     (1u << 7)
#define CH32_I2C_STAR1_BERR    (1u << 8)
#define CH32_I2C_STAR1_ARLO    (1u << 9)   /* arbitration lost              */
#define CH32_I2C_STAR1_AF      (1u << 10)  /* acknowledge failure = NACK    */
#define CH32_I2C_STAR1_OVR     (1u << 11)

#define CH32_I2C_STAR2_MSL     (1u << 0)   /* master mode                   */
#define CH32_I2C_STAR2_BUSY    (1u << 1)
#define CH32_I2C_STAR2_TRA     (1u << 2)   /* transmitting                  */

#define CH32_I2C_CKCFGR_CCR_MASK 0x0FFFu
#define CH32_I2C_CKCFGR_DUTY     (1u << 14) /* fast mode 16/9 instead of 2/1 */
#define CH32_I2C_CKCFGR_FS       (1u << 15) /* fast mode                     */

/* APB1 */
#define CH32_RCC_APB1_I2C1 (1u << 21)
#define CH32_RCC_APB1_I2C2 (1u << 22)

/* ------------------------------------------------------------------ SPI */
/* SPI1 is on APB2, SPI2/SPI3 on APB1. Like the I2C block the registers are
 * 16-bit in 32-bit slots. Only what a master transfer needs is named; the CRC
 * and I2S registers are left out. */
#define CH32_SPI1_BASE (CH32_APB2_BASE + 0x3000u)
#define CH32_SPI2_BASE (CH32_APB1_BASE + 0x3800u)
#define CH32_SPI3_BASE (CH32_APB1_BASE + 0x3C00u)

#define CH32_SPI_CTLR1(b) CH32_REG16((b) + 0x00u)
#define CH32_SPI_CTLR2(b) CH32_REG16((b) + 0x04u)
#define CH32_SPI_STATR(b) CH32_REG16((b) + 0x08u)
#define CH32_SPI_DATAR(b) CH32_REG16((b) + 0x0Cu)

#define CH32_SPI_CTLR1_CPHA      (1u << 0)
#define CH32_SPI_CTLR1_CPOL      (1u << 1)
#define CH32_SPI_CTLR1_MSTR      (1u << 2)
#define CH32_SPI_CTLR1_BR_SHIFT  3          /* divider = 2^(BR+1)            */
#define CH32_SPI_CTLR1_BR_MASK   (0x7u << 3)
#define CH32_SPI_CTLR1_SPE       (1u << 6)
#define CH32_SPI_CTLR1_LSBFIRST  (1u << 7)
#define CH32_SPI_CTLR1_SSI       (1u << 8)  /* the value NSS reads as        */
#define CH32_SPI_CTLR1_SSM       (1u << 9)  /* NSS from SSI, not from a pin  */
#define CH32_SPI_CTLR1_RXONLY    (1u << 10)
#define CH32_SPI_CTLR1_DFF       (1u << 11) /* 16-bit frames                 */
#define CH32_SPI_CTLR1_BIDIOE    (1u << 14)
#define CH32_SPI_CTLR1_BIDIMODE  (1u << 15)

#define CH32_SPI_STATR_RXNE      (1u << 0)
#define CH32_SPI_STATR_TXE       (1u << 1)
#define CH32_SPI_STATR_MODF      (1u << 5)
#define CH32_SPI_STATR_OVR       (1u << 6)
#define CH32_SPI_STATR_BSY       (1u << 7)

/* APB1 */
#define CH32_RCC_APB1_SPI2 (1u << 14)
#define CH32_RCC_APB1_SPI3 (1u << 15)

/* ---------------------------------------------------------------- FLASH */
/* Flash controller registers (not the flash memory itself). */
#define CH32_FLASH_BASE  (CH32_AHB_BASE + 0x2000u)
#define CH32_FLASH_ACTLR CH32_REG32(CH32_FLASH_BASE + 0x00u)
#define CH32_FLASH_ACTLR_LATENCY_MASK 0x3u

/* ----------------------------------------------------------------- AFIO */
#define CH32_AFIO_BASE  (CH32_APB2_BASE + 0x0000u)
#define CH32_AFIO_ECR   CH32_REG32(CH32_AFIO_BASE + 0x00u)
#define CH32_AFIO_PCFR1 CH32_REG32(CH32_AFIO_BASE + 0x04u)  /* peripheral remap */
#define CH32_AFIO_PCFR2 CH32_REG32(CH32_AFIO_BASE + 0x1Cu)

/* ----------------------------------------------------------------- GPIO */
/* Ports are 0x400 apart starting at PA, whether or not the port exists. */
#define CH32_GPIO_BASE(port) (CH32_APB2_BASE + 0x0800u + 0x400u * (uint32_t)(port))
#define CH32_GPIO_CFGLR(p)   CH32_REG32(CH32_GPIO_BASE(p) + 0x00u)
#define CH32_GPIO_CFGHR(p)   CH32_REG32(CH32_GPIO_BASE(p) + 0x04u)
#define CH32_GPIO_INDR(p)    CH32_REG32(CH32_GPIO_BASE(p) + 0x08u)
#define CH32_GPIO_OUTDR(p)   CH32_REG32(CH32_GPIO_BASE(p) + 0x0Cu)
#define CH32_GPIO_BSHR(p)    CH32_REG32(CH32_GPIO_BASE(p) + 0x10u)
#define CH32_GPIO_BCR(p)     CH32_REG32(CH32_GPIO_BASE(p) + 0x14u)
#define CH32_GPIO_LCKR(p)    CH32_REG32(CH32_GPIO_BASE(p) + 0x18u)
/* 24-pin ports (X033/X035) only: config and set for bits 16..23. */
#define CH32_GPIO_CFGXR(p)   CH32_REG32(CH32_GPIO_BASE(p) + 0x1Cu)
#define CH32_GPIO_BSXR(p)    CH32_REG32(CH32_GPIO_BASE(p) + 0x20u)

/* Pin configuration nibble: (CNF << 2) | MODE, four bits per pin. */
#define CH32_GPIO_CFG_IN_ANALOG   0x0u
#define CH32_GPIO_CFG_IN_FLOAT    0x4u
#define CH32_GPIO_CFG_IN_PULL     0x8u  /* OUTDR bit picks up (1) or down (0) */
#define CH32_GPIO_CFG_OUT_PP_10M  0x1u
#define CH32_GPIO_CFG_OUT_OD_10M  0x5u
#define CH32_GPIO_CFG_AF_PP_50M   0xBu
#define CH32_GPIO_CFG_AF_OD_50M   0xFu

/* ---------------------------------------------------------------- USART */
#define CH32_USART1_BASE (CH32_APB2_BASE + 0x3800u)
#define CH32_USART2_BASE (CH32_APB1_BASE + 0x4400u)
#define CH32_USART3_BASE (CH32_APB1_BASE + 0x4800u)
#define CH32_USART4_BASE (CH32_APB1_BASE + 0x4C00u)   /* UART4 */
#define CH32_USART5_BASE (CH32_APB1_BASE + 0x5000u)   /* UART5 */

#define CH32_USART_STATR(b) CH32_REG16((b) + 0x00u)
#define CH32_USART_DATAR(b) CH32_REG16((b) + 0x04u)
#define CH32_USART_BRR(b)   CH32_REG16((b) + 0x08u)
#define CH32_USART_CTLR1(b) CH32_REG16((b) + 0x0Cu)
#define CH32_USART_CTLR2(b) CH32_REG16((b) + 0x10u)
#define CH32_USART_CTLR3(b) CH32_REG16((b) + 0x14u)

#define CH32_USART_STATR_PE   (1u << 0)
#define CH32_USART_STATR_FE   (1u << 1)
#define CH32_USART_STATR_NE   (1u << 2)
#define CH32_USART_STATR_ORE  (1u << 3)
#define CH32_USART_STATR_IDLE (1u << 4)
#define CH32_USART_STATR_RXNE (1u << 5)
#define CH32_USART_STATR_TC   (1u << 6)
#define CH32_USART_STATR_TXE  (1u << 7)

#define CH32_USART_CTLR1_RE     (1u << 2)
#define CH32_USART_CTLR1_TE     (1u << 3)
#define CH32_USART_CTLR1_RXNEIE (1u << 5)
#define CH32_USART_CTLR1_TXEIE  (1u << 7)
#define CH32_USART_CTLR1_PCE    (1u << 10)
#define CH32_USART_CTLR1_PS     (1u << 9)
#define CH32_USART_CTLR1_M      (1u << 12)
#define CH32_USART_CTLR1_UE     (1u << 13)

#define CH32_USART_CTLR2_STOP_1   (0u << 12)
#define CH32_USART_CTLR2_STOP_0P5 (1u << 12)
#define CH32_USART_CTLR2_STOP_2   (2u << 12)
#define CH32_USART_CTLR2_STOP_1P5 (3u << 12)

/* -------------------------------------------------------------- SysTick */
/* Same offsets on every family; only the CNT/CMP width differs, and CMP sits
 * at 0x10 either way (the 32-bit layout pads CNT to eight bytes). */
#define CH32_SYSTICK_BASE 0xE000F000u
#define CH32_SYSTICK_CTLR CH32_REG32(CH32_SYSTICK_BASE + 0x00u)
#define CH32_SYSTICK_SR   CH32_REG32(CH32_SYSTICK_BASE + 0x04u)
#define CH32_SYSTICK_CNT  CH32_REG32(CH32_SYSTICK_BASE + 0x08u)  /* low word */
#define CH32_SYSTICK_CMP  CH32_REG32(CH32_SYSTICK_BASE + 0x10u)  /* low word */
#if CH32_SYSTICK_64
#define CH32_SYSTICK_CNT_HI CH32_REG32(CH32_SYSTICK_BASE + 0x0Cu)
#define CH32_SYSTICK_CMP_HI CH32_REG32(CH32_SYSTICK_BASE + 0x14u)
#endif

#define CH32_SYSTICK_CTLR_STE   (1u << 0)  /* counter enable                 */
#define CH32_SYSTICK_CTLR_STIE  (1u << 1)  /* interrupt enable               */
#define CH32_SYSTICK_CTLR_STCLK (1u << 2)  /* 1 = HCLK, 0 = HCLK/8           */

/* ------------------------------------------------------- PFIC (like NVIC) */
#define CH32_PFIC_BASE    0xE000E000u
#define CH32_PFIC_IENR(i) CH32_REG32(CH32_PFIC_BASE + 0x100u + 4u * (i))
#define CH32_PFIC_IRER(i) CH32_REG32(CH32_PFIC_BASE + 0x180u + 4u * (i))
#define CH32_PFIC_IPRIOR(n) CH32_REG8(CH32_PFIC_BASE + 0x400u + (n))

static inline void ch32_irq_enable(uint32_t irqn)
{
    CH32_PFIC_IENR(irqn >> 5) = 1u << (irqn & 31u);
}

static inline void ch32_irq_disable(uint32_t irqn)
{
    CH32_PFIC_IRER(irqn >> 5) = 1u << (irqn & 31u);
}

/* ------------------------------------------------------------------ ADC */
/* Layout is the same on every family the platform builds for; only the
 * conversion width differs (CH32_ADC_BITS, from build.core_defines). */
#define CH32_ADC1_BASE   (CH32_APB2_BASE + 0x2400u)
#define CH32_ADC_STATR   CH32_REG32(CH32_ADC1_BASE + 0x00u)
#define CH32_ADC_CTLR1   CH32_REG32(CH32_ADC1_BASE + 0x04u)
#define CH32_ADC_CTLR2   CH32_REG32(CH32_ADC1_BASE + 0x08u)
#define CH32_ADC_SAMPTR1 CH32_REG32(CH32_ADC1_BASE + 0x0Cu)  /* channels 10..17 */
#define CH32_ADC_SAMPTR2 CH32_REG32(CH32_ADC1_BASE + 0x10u)  /* channels 0..9   */
#define CH32_ADC_RSQR1   CH32_REG32(CH32_ADC1_BASE + 0x2Cu)
#define CH32_ADC_RSQR3   CH32_REG32(CH32_ADC1_BASE + 0x34u)
#define CH32_ADC_RDATAR  CH32_REG32(CH32_ADC1_BASE + 0x4Cu)

#define CH32_ADC_STATR_EOC   (1u << 1)
#define CH32_ADC_CTLR2_ADON    (1u << 0)
#define CH32_ADC_CTLR2_CAL     (1u << 2)
#define CH32_ADC_CTLR2_RSTCAL  (1u << 3)
#define CH32_ADC_CTLR2_EXTSEL_SWSTART (7u << 17)
#define CH32_ADC_CTLR2_EXTTRIG (1u << 20)
#define CH32_ADC_CTLR2_SWSTART (1u << 22)
/* RCC_CFGR0 ADCPRE: 00=/2 01=/4 10=/6 11=/8. ADCCLK must stay under 14 MHz. */
#define CH32_RCC_CFGR0_ADCPRE_MASK (0x3u << 14)
#define CH32_RCC_CFGR0_ADCPRE(n)   ((uint32_t)(n) << 14)

/* ----------------------------------------------------------------- EXTI */
#define CH32_EXTI_BASE   (CH32_APB2_BASE + 0x0400u)
#define CH32_EXTI_INTENR CH32_REG32(CH32_EXTI_BASE + 0x00u)
#define CH32_EXTI_EVENR  CH32_REG32(CH32_EXTI_BASE + 0x04u)
#define CH32_EXTI_RTENR  CH32_REG32(CH32_EXTI_BASE + 0x08u)
#define CH32_EXTI_FTENR  CH32_REG32(CH32_EXTI_BASE + 0x0Cu)
#define CH32_EXTI_SWIEVR CH32_REG32(CH32_EXTI_BASE + 0x10u)
#define CH32_EXTI_INTFR  CH32_REG32(CH32_EXTI_BASE + 0x14u)
/* Which port drives EXTI line n: four lines per word, four bits each. */
#define CH32_AFIO_EXTICR(n) CH32_REG32(CH32_AFIO_BASE + 0x08u + 4u * (n))

/* ---------------------------------------------------------------- timers */
/* TIM1 is the advanced timer on APB2; TIM2/TIM3 are general purpose on APB1.
 * The register block is the same for all of them. */
#define CH32_TIM1_BASE (CH32_APB2_BASE + 0x2C00u)
#define CH32_TIM2_BASE (CH32_APB1_BASE + 0x0000u)
#define CH32_TIM3_BASE (CH32_APB1_BASE + 0x0400u)

#define CH32_TIM_CTLR1(b)   CH32_REG16((b) + 0x00u)
#define CH32_TIM_CHCTLR1(b) CH32_REG16((b) + 0x18u)   /* channels 1 and 2 */
#define CH32_TIM_CHCTLR2(b) CH32_REG16((b) + 0x1Cu)   /* channels 3 and 4 */
#define CH32_TIM_CCER(b)    CH32_REG16((b) + 0x20u)
#define CH32_TIM_CNT(b)     CH32_REG16((b) + 0x24u)
#define CH32_TIM_PSC(b)     CH32_REG16((b) + 0x28u)
#define CH32_TIM_ATRLR(b)   CH32_REG16((b) + 0x2Cu)   /* auto-reload */
#define CH32_TIM_CHCVR(b, ch) CH32_REG16((b) + 0x34u + 4u * ((ch) - 1u))
#define CH32_TIM_BDTR(b)    CH32_REG16((b) + 0x44u)   /* TIM1 only */

#define CH32_TIM_CTLR1_CEN  (1u << 0)
#define CH32_TIM_CTLR1_ARPE (1u << 7)
#define CH32_TIM_BDTR_MOE   (1u << 15)
/* PWM mode 1 with preload, in the low or high half of a CHCTLR word. */
#define CH32_TIM_OCMODE_PWM1 0x68u

#define CH32_RCC_APB1_TIM2 (1u << 0)
#define CH32_RCC_APB1_TIM3 (1u << 1)
