/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: ch32-riscv-ug/ch32-device-data tables, pinned in vendor/ch32-device-data.lock.toml
 *
 * CH32X315: what EVT's SystemInit writes before configuring the
 * clock. Order matters, and so does doing it at all - PLLSRC and
 * PLLMULL cannot be changed while PLLON is set, so a PLL left running
 * by a previous program would otherwise keep its configuration.
 */
#pragma once

#define CH32_CLOCK_INIT_RESET() do { \
    CH32_REG32(0x40021000u) |= 0x00000001u; \
    while ((CH32_REG32(0x40021000u) & 0x00000002u) != 0x00000002u) {} \
    CH32_REG32(0x40021004u) &= 0xfffffffcu; \
    while ((CH32_REG32(0x40021004u) & 0x0000000cu) != 0x00000000u) {} \
    CH32_REG32(0x40021004u) &= 0x00000003u; \
    CH32_REG32(0x40021000u) &= 0x7ffeffffu; \
    CH32_REG32(0x40021000u) &= 0xeaf3feffu; \
    CH32_REG32(0x40021008u) = 0x008d0000u; \
    CH32_REG32(0x4002102cu) &= 0x00c0fc00u; \
    CH32_REG32(0x4002102cu) |= 0x10000000u; \
    CH32_REG32(0x40022004u) = 0x45670123u; \
    CH32_REG32(0x40022004u) = 0xcdef89abu; \
    CH32_REG32(0x40022024u) = 0x45670123u; \
    CH32_REG32(0x40022024u) = 0xcdef89abu; \
    CH32_REG32(0x40022000u) |= 0x00000800u; \
    CH32_REG32(0x40022010u) |= 0x00008080u; \
} while (0)
