/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: ch32-riscv-ug/ch32-device-data tables, pinned in vendor/ch32-device-data.lock.toml
 *
 * CH32X035: what EVT's SystemInit writes before configuring the
 * clock. Order matters, and so does doing it at all - PLLSRC and
 * PLLMULL cannot be changed while PLLON is set, so a PLL left running
 * by a previous program would otherwise keep its configuration.
 */
#pragma once

#define CH32_CLOCK_INIT_RESET() do { \
    CH32_REG32(0x40021000u) |= 0x00000001u; \
    CH32_REG32(0x40021004u) |= 0x00000050u; \
    CH32_REG32(0x40021004u) &= 0xf8ffff5fu; \
} while (0)
