/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: tools/generate/interrupts/interrupts.csv (variant m030)
 * EXTI vector grouping: handler name and the pin bits it covers. */
#pragma once

#define CH32_EXTI_GROUP_COUNT 2

/* X(handler, mask, irqn) for every EXTI vector this variant has. */
#define CH32_EXTI_GROUPS(X) \
    X(EXTI7_0_IRQHandler, 0x000000ffu, CH32_IRQN_EXTI7_0) \
    X(EXTI15_8_IRQHandler, 0x0000ff00u, CH32_IRQN_EXTI15_8) \
    /* end */
