/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: tools/generate/interrupts/interrupts.csv (variant v307_d8)
 * EXTI vector grouping: handler name and the pin bits it covers. */
#pragma once

#define CH32_EXTI_GROUP_COUNT 7

/* X(handler, mask, irqn) for every EXTI vector this variant has. */
#define CH32_EXTI_GROUPS(X) \
    X(EXTI0_IRQHandler, 0x00000001u, CH32_IRQN_EXTI0) \
    X(EXTI1_IRQHandler, 0x00000002u, CH32_IRQN_EXTI1) \
    X(EXTI2_IRQHandler, 0x00000004u, CH32_IRQN_EXTI2) \
    X(EXTI3_IRQHandler, 0x00000008u, CH32_IRQN_EXTI3) \
    X(EXTI4_IRQHandler, 0x00000010u, CH32_IRQN_EXTI4) \
    X(EXTI9_5_IRQHandler, 0x000003e0u, CH32_IRQN_EXTI9_5) \
    X(EXTI15_10_IRQHandler, 0x0000fc00u, CH32_IRQN_EXTI15_10) \
    /* end */
