/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: tools/generate/interrupts/interrupts.csv (variant x035)
 * Slot index in the vector table == interrupt number for PFIC. */
#pragma once

#define CH32_IRQN_NMI                      2
#define CH32_IRQN_HardFault                3
#define CH32_IRQN_Ecall_M_Mode             5
#define CH32_IRQN_Ecall_U_Mode             8
#define CH32_IRQN_Break_Point              9
#define CH32_IRQN_SysTick                  12
#define CH32_IRQN_SW                       14
#define CH32_IRQN_WWDG                     16
#define CH32_IRQN_PVD                      17
#define CH32_IRQN_FLASH                    18
#define CH32_IRQN_EXTI7_0                  20
#define CH32_IRQN_AWU                      21
#define CH32_IRQN_DMA1_Channel1            22
#define CH32_IRQN_DMA1_Channel2            23
#define CH32_IRQN_DMA1_Channel3            24
#define CH32_IRQN_DMA1_Channel4            25
#define CH32_IRQN_DMA1_Channel5            26
#define CH32_IRQN_DMA1_Channel6            27
#define CH32_IRQN_DMA1_Channel7            28
#define CH32_IRQN_ADC1                     29
#define CH32_IRQN_I2C1_EV                  30
#define CH32_IRQN_I2C1_ER                  31
#define CH32_IRQN_USART1                   32
#define CH32_IRQN_SPI1                     33
#define CH32_IRQN_TIM1_BRK                 34
#define CH32_IRQN_TIM1_UP                  35
#define CH32_IRQN_TIM1_TRG_COM             36
#define CH32_IRQN_TIM1_CC                  37
#define CH32_IRQN_TIM2_UP                  38
#define CH32_IRQN_USART2                   39
#define CH32_IRQN_EXTI15_8                 40
#define CH32_IRQN_EXTI25_16                41
#define CH32_IRQN_USART3                   42
#define CH32_IRQN_USART4                   43
#define CH32_IRQN_DMA1_Channel8            44
#define CH32_IRQN_USBFS                    45
#define CH32_IRQN_USBFSWakeUp              46
#define CH32_IRQN_PIOC                     47
#define CH32_IRQN_OPA                      48
#define CH32_IRQN_USBPD                    49
#define CH32_IRQN_USBPDWakeUp              50
#define CH32_IRQN_TIM2_CC                  51
#define CH32_IRQN_TIM2_TRG_COM             52
#define CH32_IRQN_TIM2_BRK                 53
#define CH32_IRQN_TIM3                     54
