/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: tools/generate/interrupts/interrupts.csv (variant v00x)
 * Slot index in the vector table == interrupt number for PFIC. */
#pragma once

#define CH32_IRQN_NMI                      2
#define CH32_IRQN_HardFault                3
#define CH32_IRQN_SysTick                  12
#define CH32_IRQN_SW                       14
#define CH32_IRQN_WWDG                     16
#define CH32_IRQN_PVD                      17
#define CH32_IRQN_FLASH                    18
#define CH32_IRQN_RCC                      19
#define CH32_IRQN_EXTI7_0                  20
#define CH32_IRQN_AWU                      21
#define CH32_IRQN_DMA1_Channel1            22
#define CH32_IRQN_DMA1_Channel2            23
#define CH32_IRQN_DMA1_Channel3            24
#define CH32_IRQN_DMA1_Channel4            25
#define CH32_IRQN_DMA1_Channel5            26
#define CH32_IRQN_DMA1_Channel6            27
#define CH32_IRQN_DMA1_Channel7            28
#define CH32_IRQN_ADC1                     29
#define CH32_IRQN_I2C1_EV                  30
#define CH32_IRQN_I2C1_ER                  31
#define CH32_IRQN_USART1                   32
#define CH32_IRQN_SPI1                     33
#define CH32_IRQN_TIM1_BRK                 34
#define CH32_IRQN_TIM1_UP                  35
#define CH32_IRQN_TIM1_TRG_COM             36
#define CH32_IRQN_TIM1_CC                  37
#define CH32_IRQN_TIM2                     38
#define CH32_IRQN_USART2                   39
#define CH32_IRQN_OPCM                     40
