/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: ch32-riscv-ug/ch32-device-data tables, pinned in vendor/ch32-device-data.lock.toml
 *
 * CH32X033 pin map: the union of all 1 part numbers in the
 * series, so the same header serves the ANY menu entry and every SKU.
 *
 * Pin numbers are port-encoded (ADR-0010): pin = (port << 5) | bit.
 * The valid set is SPARSE. NUM_DIGITAL_PINS is one past the highest pin
 * number, NOT a pad count, and 0..NUM_DIGITAL_PINS-1 is not a usable
 * loop range - test with digitalPinIsValid(pin).
 *
 * A pad missing from a given package is left unbonded: writing it only
 * touches a register bit with nothing attached, which is harmless.
 *
 * Exception, errata x035-pc10-pc17-bonded: PC10/PC17 and PC11/PC16 are
 * internally bonded pairs sharing one lead; never drive both halves of a
 * pair. The core marks PC10/PC11 as the never-driven side.
 */
#pragma once

#include "ch32_pins.h"

#define CH32_VARIANT_CH32X033 1

/* ---- GPIO pads: 21 in the series, 21 of them on every part ---- */
#define PA0  CH32_PIN(0,  0)
#define PA1  CH32_PIN(0,  1)
#define PA2  CH32_PIN(0,  2)
#define PA3  CH32_PIN(0,  3)
#define PA4  CH32_PIN(0,  4)
#define PA5  CH32_PIN(0,  5)
#define PA6  CH32_PIN(0,  6)
#define PA7  CH32_PIN(0,  7)
#define PA9  CH32_PIN(0,  9)
#define PA10 CH32_PIN(0, 10)
#define PA11 CH32_PIN(0, 11)
#define PB0  CH32_PIN(1,  0)
#define PB1  CH32_PIN(1,  1)
#define PB7  CH32_PIN(1,  7)
#define PC3  CH32_PIN(2,  3)
#define PC10 CH32_PIN(2, 10)
#define PC11 CH32_PIN(2, 11)
#define PC16 CH32_PIN(2, 16)
#define PC17 CH32_PIN(2, 17)
#define PC18 CH32_PIN(2, 18)
#define PC19 CH32_PIN(2, 19)

/* Bit n set = P<port>n is bonded out on at least one part in the series. */
#define CH32_PORT_MASK_A 0x00000effu
#define CH32_PORT_MASK_B 0x00000083u
#define CH32_PORT_MASK_C 0x000f0c08u
#define CH32_PORT_MASK_D 0x00000000u   /* port absent */
#define CH32_PORT_MASK_E 0x00000000u   /* port absent */
#define CH32_PORT_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_MASK(port) ( \
    (port) == 0 ? CH32_PORT_MASK_A : \
    (port) == 1 ? CH32_PORT_MASK_B : \
    (port) == 2 ? CH32_PORT_MASK_C : \
    (port) == 3 ? CH32_PORT_MASK_D : \
    (port) == 4 ? CH32_PORT_MASK_E : \
    (port) == 5 ? CH32_PORT_MASK_F : \
    0u)

/* Bit n set = P<port>n is bonded out on EVERY part in the series,
 * i.e. the pins a sketch built for the ANY menu entry can rely on. */
#define CH32_PORT_COMMON_MASK_A 0x00000effu
#define CH32_PORT_COMMON_MASK_B 0x00000083u
#define CH32_PORT_COMMON_MASK_C 0x000f0c08u
#define CH32_PORT_COMMON_MASK_D 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_E 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK(port) ( \
    (port) == 0 ? CH32_PORT_COMMON_MASK_A : \
    (port) == 1 ? CH32_PORT_COMMON_MASK_B : \
    (port) == 2 ? CH32_PORT_COMMON_MASK_C : \
    (port) == 3 ? CH32_PORT_COMMON_MASK_D : \
    (port) == 4 ? CH32_PORT_COMMON_MASK_E : \
    (port) == 5 ? CH32_PORT_COMMON_MASK_F : \
    0u)

/* Register bits that must never be driven; see the errata note above. */
#define CH32_UNUSABLE_PIN_COUNT 2
#define CH32_UNUSABLE_PINS { \
    CH32_PIN(2, 10) /* PC10, x035-pc10-pc17-bonded */, \
    CH32_PIN(2, 11) /* PC11, x035-pc10-pc17-bonded */, \
    }

#define NUM_DIGITAL_PINS 84   /* highest pin number + 1, not a pad count */
#define PINS_COUNT       NUM_DIGITAL_PINS
#define CH32_GPIO_COUNT  21   /* actual pads in the series */

/* ---- ADC1 analog inputs (11 channels) ---- */
/* Channels [10, 11, 12] are not bonded out in this series. */
#define NUM_ANALOG_INPUTS 14   /* highest channel + 1; see the gaps above */
#define A0   PA0
#define A1   PA1
#define A2   PA2
#define A3   PA3
#define A4   PA4
#define A5   PA5
#define A6   PA6
#define A7   PA7
#define A8   PB0
#define A9   PB1
#define A13  PC3
#define CH32_PIN_TO_ADC_CHANNEL(p) ( \
    (p) == PA0 ? 0 : \
    (p) == PA1 ? 1 : \
    (p) == PA2 ? 2 : \
    (p) == PA3 ? 3 : \
    (p) == PA4 ? 4 : \
    (p) == PA5 ? 5 : \
    (p) == PA6 ? 6 : \
    (p) == PA7 ? 7 : \
    (p) == PB0 ? 8 : \
    (p) == PB1 ? 9 : \
    (p) == PC3 ? 13 : \
    NOT_AN_ANALOG_PIN)
#define CH32_ADC_CHANNEL_TO_PIN(c) ( \
    (c) == 0 ? PA0 : \
    (c) == 1 ? PA1 : \
    (c) == 2 ? PA2 : \
    (c) == 3 ? PA3 : \
    (c) == 4 ? PA4 : \
    (c) == 5 ? PA5 : \
    (c) == 6 ? PA6 : \
    (c) == 7 ? PA7 : \
    (c) == 8 ? PB0 : \
    (c) == 9 ? PB1 : \
    (c) == 13 ? PC3 : \
    NOT_A_PIN)

/* ---- USART pins (device-data; one route per USART, chosen for
 *      the whole series - see choose_uarts in generate.py) ---- */
/* USART1: route remap-1, on every part */
#define CH32_SERIAL1_TX PA10
#define CH32_SERIAL1_RX PA11
#define CH32_SERIAL1_HANDLER USART1_IRQHandler
#define CH32_SERIAL1_IRQ CH32_IRQN_USART1
#define CH32_SERIAL1_REMAP_MASK 0x00000060u
#define CH32_SERIAL1_REMAP_VAL  0x00000020u
/* SERIAL1 routes for setRoute()/setPins(): route number, then TX, RX */
#define CH32_SERIAL1_ROUTE_COUNT 1
#define CH32_SERIAL1_ROUTES { \
    { 1, { PA10, PA11, CH32_ROUTE_NO_PIN }, 0x00000020u, 0x00000000u }, \
}
/* USART2: route default, on every part */
#define CH32_SERIAL2_TX PA2
#define CH32_SERIAL2_RX PA3
#define CH32_SERIAL2_HANDLER USART2_IRQHandler
#define CH32_SERIAL2_IRQ CH32_IRQN_USART2
#define CH32_SERIAL2_REMAP_MASK 0x00000380u
#define CH32_SERIAL2_REMAP_VAL  0x00000000u
/* SERIAL2 routes for setRoute()/setPins(): route number, then TX, RX */
#define CH32_SERIAL2_ROUTE_COUNT 1
#define CH32_SERIAL2_ROUTES { \
    { 0, { PA2, PA3, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00000000u }, \
}
/* USART4: route default, on every part */
#define CH32_SERIAL4_TX PB0
#define CH32_SERIAL4_RX PB1
#define CH32_SERIAL4_HANDLER USART4_IRQHandler
#define CH32_SERIAL4_IRQ CH32_IRQN_USART4
#define CH32_SERIAL4_REMAP_MASK 0x00007000u
#define CH32_SERIAL4_REMAP_VAL  0x00000000u
/* SERIAL4 routes for setRoute()/setPins(): route number, then TX, RX */
#define CH32_SERIAL4_ROUTE_COUNT 2
#define CH32_SERIAL4_ROUTES { \
    { 0, { PB0, PB1, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00000000u }, \
    { 1, { PA5, PA9, CH32_ROUTE_NO_PIN }, 0x00001000u, 0x00000000u }, \
}
#ifndef CH32_SERIAL_DEFAULT
#define CH32_SERIAL_DEFAULT 2
#endif

/* ---- I2C pins (device-data; one route per instance,
 *      chosen for the whole series - see choose_i2cs) ---- */
/* I2C1: route default, on every part */
#define CH32_I2C1_SCL PA10
#define CH32_I2C1_SDA PA11
#define CH32_I2C1_REMAP_MASK 0x0000001cu
#define CH32_I2C1_REMAP_VAL  0x00000000u
/* I2C1 routes for setRoute()/setPins(): route number, then SCL, SDA */
#define CH32_I2C1_ROUTE_COUNT 5
#define CH32_I2C1_ROUTES { \
    { 0, { PA10, PA11, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00000000u }, \
    { 2, { PC16, PC17, CH32_ROUTE_NO_PIN }, 0x00000008u, 0x00000000u }, \
    { 3, { PC19, PC18, CH32_ROUTE_NO_PIN }, 0x0000000cu, 0x00000000u }, \
    { 4, { PC17, PC16, CH32_ROUTE_NO_PIN }, 0x00000010u, 0x00000000u }, \
    { 5, { PC18, PC19, CH32_ROUTE_NO_PIN }, 0x00000014u, 0x00000000u }, \
}
/* Arduino's standard names for the first bus (Wire). */
#ifndef PIN_WIRE_SCL
#define PIN_WIRE_SCL CH32_I2C1_SCL
#define PIN_WIRE_SDA CH32_I2C1_SDA
#define SCL PIN_WIRE_SCL
#define SDA PIN_WIRE_SDA
#endif

/* ---- SPI pins (device-data; one route per instance,
 *      chosen for the whole series - see choose_spis).
 *      NSS is not listed: Arduino drives chip select as a GPIO. ---- */
/* SPI1: route default, on every part */
#define CH32_SPI1_SCK PA5
#define CH32_SPI1_MISO PA6
#define CH32_SPI1_MOSI PA7
#define CH32_SPI1_REMAP_MASK 0x00000003u
#define CH32_SPI1_REMAP_VAL  0x00000000u
/* SPI1 routes for setRoute()/setPins(): route number, then SCK, MISO, MOSI */
#define CH32_SPI1_ROUTE_COUNT 2
#define CH32_SPI1_ROUTES { \
    { 0, { PA5, PA6, PA7 }, 0x00000000u, 0x00000000u }, \
    { 2, { PA11, PA9, PA10 }, 0x00000002u, 0x00000000u }, \
}
/* Arduino's standard names for the first bus (SPI). */
#ifndef PIN_SPI_SCK
#define PIN_SPI_SCK CH32_SPI1_SCK
#define PIN_SPI_MISO CH32_SPI1_MISO
#define PIN_SPI_MOSI CH32_SPI1_MOSI
#define SCK PIN_SPI_SCK
#define MISO PIN_SPI_MISO
#define MOSI PIN_SPI_MOSI
/* No SS: device-data names no NSS pad on this route. */
#endif

/* ---- PWM: 7 pads on TIM1/TIM2/TIM3, default route ---- */
#define CH32_PWM_PIN_COUNT 7
#define CH32_PWM_PIN_TO_TIMER(p) ( \
    (p) == PC16 ? 1 : \
    (p) == PA0 ? 2 : \
    (p) == PA1 ? 2 : \
    (p) == PA2 ? 2 : \
    (p) == PA3 ? 2 : \
    (p) == PA6 ? 3 : \
    (p) == PA7 ? 3 : \
    0)
#define CH32_PWM_PIN_TO_CHANNEL(p) ( \
    (p) == PC16 ? 4 : \
    (p) == PA0 ? 1 : \
    (p) == PA1 ? 2 : \
    (p) == PA2 ? 3 : \
    (p) == PA3 ? 4 : \
    (p) == PA6 ? 1 : \
    (p) == PA7 ? 2 : \
    0)

/* ---- tone(): TIM3, which is also a PWM timer here, so
 *      analogWrite() on PA6, PA7
 *      is disturbed while a tone plays. ---- */
#define CH32_TONE_TIMER 3
#define CH32_TONE_TIMER_BASE CH32_TIM3_BASE
#define CH32_TONE_TIMER_RCC CH32_RCC_APB1_TIM3
#define CH32_TONE_TIMER_ON_APB2 0
#define CH32_TONE_TIMER_IRQ CH32_IRQN_TIM3
#define CH32_TONE_TIMER_HANDLER TIM3_IRQHandler
#define CH32_TONE_SHARES_PWM 1
#define CH32_TONE_TIMER_BITS 16

/* ---- Servo: TIM2, which is also a PWM timer here, so
 *      analogWrite() on PA0, PA1, PA2, PA3
 *      is disturbed while a servo is attached. ---- */
#define CH32_SERVO_TIMER 2
#define CH32_SERVO_TIMER_BASE CH32_TIM2_BASE
#define CH32_SERVO_TIMER_RCC CH32_RCC_APB1_TIM2
#define CH32_SERVO_TIMER_ON_APB2 0
#define CH32_SERVO_TIMER_IRQ CH32_IRQN_TIM2_UP
#define CH32_SERVO_TIMER_HANDLER TIM2_UP_IRQHandler
#define CH32_SERVO_SHARES_PWM 1
#define CH32_SERVO_TIMER_BITS 16

/* Generic boards have no on-board LED. This placeholder only exists so
 * that the stock examples compile; it is the lowest-numbered pad present
 * on every part in the series. Override it per board or on the command
 * line: --build-property build.extra_flags=-DLED_BUILTIN=PC13 */
#ifndef LED_BUILTIN
#define LED_BUILTIN PA0
#endif
