/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: ch32-device-data tables @ git 8c09ab446f510a1ab056dad4c7f3ae5fbdc91ad9
 *
 * CH32X033 pin map: the union of all 1 part numbers in the
 * series, so the same header serves the ANY menu entry and every SKU.
 *
 * Pin numbers are port-encoded (ADR-0010): pin = (port << 5) | bit.
 * The valid set is SPARSE. NUM_DIGITAL_PINS is one past the highest pin
 * number, NOT a pad count, and 0..NUM_DIGITAL_PINS-1 is not a usable
 * loop range - test with digitalPinIsValid(pin).
 *
 * A pad missing from a given package is left unbonded: writing it only
 * touches a register bit with nothing attached, which is harmless.
 *
 * Exception, errata x035-pc10-pc17-bonded: PC10/PC11 have no pin of their
 * own but are internally bonded to PC17/PC16, so writing them drives a
 * real pin.
 */
#pragma once

#include "ch32_pins.h"

#define CH32_VARIANT_CH32X033 1

/* ---- GPIO pads: 19 in the series, 19 of them on every part ---- */
#define PA0  CH32_PIN(0,  0)
#define PA1  CH32_PIN(0,  1)
#define PA2  CH32_PIN(0,  2)
#define PA3  CH32_PIN(0,  3)
#define PA4  CH32_PIN(0,  4)
#define PA5  CH32_PIN(0,  5)
#define PA6  CH32_PIN(0,  6)
#define PA7  CH32_PIN(0,  7)
#define PA9  CH32_PIN(0,  9)
#define PA10 CH32_PIN(0, 10)
#define PA11 CH32_PIN(0, 11)
#define PB0  CH32_PIN(1,  0)
#define PB1  CH32_PIN(1,  1)
#define PB7  CH32_PIN(1,  7)
#define PC3  CH32_PIN(2,  3)
#define PC16 CH32_PIN(2, 16)
#define PC17 CH32_PIN(2, 17)
#define PC18 CH32_PIN(2, 18)
#define PC19 CH32_PIN(2, 19)

/* Bit n set = P<port>n is bonded out on at least one part in the series. */
#define CH32_PORT_MASK_A 0x00000effu
#define CH32_PORT_MASK_B 0x00000083u
#define CH32_PORT_MASK_C 0x000f0008u
#define CH32_PORT_MASK_D 0x00000000u   /* port absent */
#define CH32_PORT_MASK_E 0x00000000u   /* port absent */
#define CH32_PORT_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_MASK(port) ( \
    (port) == 0 ? CH32_PORT_MASK_A : \
    (port) == 1 ? CH32_PORT_MASK_B : \
    (port) == 2 ? CH32_PORT_MASK_C : \
    (port) == 3 ? CH32_PORT_MASK_D : \
    (port) == 4 ? CH32_PORT_MASK_E : \
    (port) == 5 ? CH32_PORT_MASK_F : \
    0u)

/* Bit n set = P<port>n is bonded out on EVERY part in the series,
 * i.e. the pins a sketch built for the ANY menu entry can rely on. */
#define CH32_PORT_COMMON_MASK_A 0x00000effu
#define CH32_PORT_COMMON_MASK_B 0x00000083u
#define CH32_PORT_COMMON_MASK_C 0x000f0008u
#define CH32_PORT_COMMON_MASK_D 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_E 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK(port) ( \
    (port) == 0 ? CH32_PORT_COMMON_MASK_A : \
    (port) == 1 ? CH32_PORT_COMMON_MASK_B : \
    (port) == 2 ? CH32_PORT_COMMON_MASK_C : \
    (port) == 3 ? CH32_PORT_COMMON_MASK_D : \
    (port) == 4 ? CH32_PORT_COMMON_MASK_E : \
    (port) == 5 ? CH32_PORT_COMMON_MASK_F : \
    0u)

/* Register bits that must never be driven; see the errata note above. */
#define CH32_UNUSABLE_PIN_COUNT 2
#define CH32_UNUSABLE_PINS { \
    CH32_PIN(2, 10) /* PC10, x035-pc10-pc17-bonded */, \
    CH32_PIN(2, 11) /* PC11, x035-pc10-pc17-bonded */, \
    }

#define NUM_DIGITAL_PINS 84   /* highest pin number + 1, not a pad count */
#define PINS_COUNT       NUM_DIGITAL_PINS
#define CH32_GPIO_COUNT  19   /* actual pads in the series */

/* ---- ADC1 analog inputs (11 channels) ---- */
/* Channels [10, 11, 12] are not bonded out in this series. */
#define NUM_ANALOG_INPUTS 14   /* highest channel + 1; see the gaps above */
#define A0   PA0
#define A1   PA1
#define A2   PA2
#define A3   PA3
#define A4   PA4
#define A5   PA5
#define A6   PA6
#define A7   PA7
#define A8   PB0
#define A9   PB1
#define A13  PC3
#define CH32_PIN_TO_ADC_CHANNEL(p) ( \
    (p) == PA0 ? 0 : \
    (p) == PA1 ? 1 : \
    (p) == PA2 ? 2 : \
    (p) == PA3 ? 3 : \
    (p) == PA4 ? 4 : \
    (p) == PA5 ? 5 : \
    (p) == PA6 ? 6 : \
    (p) == PA7 ? 7 : \
    (p) == PB0 ? 8 : \
    (p) == PB1 ? 9 : \
    (p) == PC3 ? 13 : \
    NOT_AN_ANALOG_PIN)
#define CH32_ADC_CHANNEL_TO_PIN(c) ( \
    (c) == 0 ? PA0 : \
    (c) == 1 ? PA1 : \
    (c) == 2 ? PA2 : \
    (c) == 3 ? PA3 : \
    (c) == 4 ? PA4 : \
    (c) == 5 ? PA5 : \
    (c) == 6 ? PA6 : \
    (c) == 7 ? PA7 : \
    (c) == 8 ? PB0 : \
    (c) == 9 ? PB1 : \
    (c) == 13 ? PC3 : \
    NOT_A_PIN)

/* ---- USART pins (device-data; one route per USART, chosen for
 *      the whole series - see choose_uarts in generate.py) ---- */
/* USART1: route remap-1, on every part */
#define CH32_SERIAL1_TX PA10
#define CH32_SERIAL1_RX PA11
#define CH32_SERIAL1_HANDLER USART1_IRQHandler
#define CH32_SERIAL1_IRQ CH32_IRQN_USART1
/* NOTE: route remap-1 needs an AFIO remap but device-data
 * has no PCFR1 field for USART1 in this series. */
/* USART2: route default, on every part */
#define CH32_SERIAL2_TX PA2
#define CH32_SERIAL2_RX PA3
#define CH32_SERIAL2_HANDLER USART2_IRQHandler
#define CH32_SERIAL2_IRQ CH32_IRQN_USART2
/* USART3: route remap-1, on every part */
#define CH32_SERIAL3_TX PC18
#define CH32_SERIAL3_RX PC19
#define CH32_SERIAL3_HANDLER USART3_IRQHandler
#define CH32_SERIAL3_IRQ CH32_IRQN_USART3
/* NOTE: route remap-1 needs an AFIO remap but device-data
 * has no PCFR1 field for USART3 in this series. */
/* USART4: route default, on every part */
#define CH32_SERIAL4_TX PB0
#define CH32_SERIAL4_RX PB1
#define CH32_SERIAL4_HANDLER USART4_IRQHandler
#define CH32_SERIAL4_IRQ CH32_IRQN_USART4
#define CH32_SERIAL_DEFAULT 2

/* Generic boards have no on-board LED. This placeholder only exists so
 * that the stock examples compile; it is the lowest-numbered pad present
 * on every part in the series. Override it per board or on the command
 * line: --build-property build.extra_flags=-DLED_BUILTIN=PC13 */
#ifndef LED_BUILTIN
#define LED_BUILTIN PA0
#endif
