"""Environment overrides for manual tests that need board-specific pins.

Which pads are free depends on the board on the bench, so a pin baked into a
sketch is wrong for everyone except whoever wrote it. The pins therefore come
from the environment, following the same convention as the other projects on
this bench:

    cd tests
    cp .env.example .env        # edit for your board
    uv run --env-file .env pytest manual/gpio_loopback/gpio_loopback.py -v -s

The defaults in each test still work, so an unset variable is not an error -
it just means "the author's board".

Pins are compile-time in Arduino, so the value cannot be pushed over serial at
runtime without making every sketch parse a config protocol. Instead a test's
conftest.py writes a small generated header into the sketch directory before
the build; arduino-cli compiles the sketch directory in place, so the sketch
just includes it.
"""
import os
import pathlib
import re

PORTS = "ABCDEF"
PIN_PORT_BITS = 5      # cores/arduino/ch32_pins.h, ADR-0010


def encode(pad: str) -> int:
    """"PA0" / "PC19" -> the port-encoded pin number the core uses.

    A plain integer is passed through, so a pad this parser does not know can
    still be given as a number.
    """
    pad = pad.strip().upper()
    if re.fullmatch(r"\d+", pad):
        return int(pad)
    m = re.fullmatch(r"P([A-F])(\d{1,2})", pad)
    if not m:
        raise ValueError(f"{pad!r} is not a pad name like PA0 or PC19, "
                         f"nor a plain pin number")
    port, bit = PORTS.index(m.group(1)), int(m.group(2))
    if bit > 23:
        raise ValueError(f"{pad!r}: bit {bit} is beyond the widest CH32 port (24)")
    return (port << PIN_PORT_BITS) | bit


def pin(name: str, default: str) -> tuple:
    """(pad name, encoded number) for one environment variable."""
    pad = os.environ.get(name, default)
    return pad, encode(pad)


def write_pin_header(sketch_dir, pins: dict, header: str = "env_config.h") -> pathlib.Path:
    """Write `#define <macro> <number>` for each entry, next to the sketch.

    Regenerated on every run and listed in .gitignore: it is a build input
    derived from the environment, not source.
    """
    lines = ["/* GENERATED by tests/manual/env_config.py - do not edit, do not commit.",
             " * Values come from the environment; see tests/.env.example.",
             " */",
             "#pragma once",
             ""]
    for macro, (pad, value) in sorted(pins.items()):
        lines.append(f"#define {macro} {value}   /* {pad} */")
    path = pathlib.Path(sketch_dir) / header
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
