#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.9"
# dependencies = ["pyserial>=3.5"]
# ///
"""Find which USART route a board actually wires to the probe's UART bridge.

`smoke.py` uses the port the variant picked, which is the one whose pins exist
on every part in the series. A given *board* may route a different one, and on a
board nobody has run before that is unknown. This drives a distinct marker out
of every plausible route in turn and reports which markers arrive.

  uv run tests/manual/uart_scan.py --board CH32X035

The sketch is generated from the same device-data tables the platform is
generated from, so the candidate list stays correct as the tables change.
Routes on pins the debugger needs (SWD) are skipped.

Environment:
  CH32_GCC_BIN   riscv-none-elf-gcc bin directory (required)
  CH32_TABLES    ch32-device-data tables directory (required)
  CH32_PROBE_RS  directory holding the probe-rs binary (default: Board Manager's)
"""
import argparse
import csv
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile
import time

REPO = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "tools" / "generate"))

# APB1 clock-enable bit per USART index; USART1 lives on APB2 instead.
APB1_BIT = {2: 17, 3: 18, 4: 19, 5: 20}
USART_BASE = {1: 0x40013800, 2: 0x40004400, 3: 0x40004800,
              4: 0x40004C00, 5: 0x40005000}
# Pads the WCH-Link needs for SWD, per series. Driving them as a UART kills the
# debug connection mid-scan.
SWD_PADS = {"CH32X033": {("C", 18), ("C", 19)}, "CH32X035": {("C", 18), ("C", 19)}}
DEFAULT_SWD = {("A", 13), ("A", 14)}


def candidates(series: str, tables: pathlib.Path):
    """[(label, usart, port, bit, remap mask, remap value)] worth trying."""
    import generate as g

    products = [r for r in csv.DictReader(open(tables / "products.csv",
                                               newline="", encoding="utf-8"))
                if r["series"] == series]
    parts = sorted(r["part_number"] for r in products)
    uarts = g.load_uart_pins(tables)
    remap = g.load_remap_fields(tables)
    skip = SWD_PADS.get(series, DEFAULT_SWD)

    seen = {}
    for part in parts:
        for (index, route), dirs in uarts.get(part, {}).items():
            if index not in USART_BASE or "TX" not in dirs:
                continue
            value = g.route_remap_value(route)
            if value is None:
                continue                       # per-pin AF, not an AFIO remap
            bits = remap.get((series, index))
            if value and not bits:
                continue                       # cannot select this route
            tx = dirs["TX"]
            if tx in skip:
                continue
            mask, val = g.remap_mask_value(bits, value) if value else (0, 0)
            label = f"U{index}-P{tx[0]}{tx[1]}"
            seen.setdefault(label, (label, index, tx[0], tx[1], mask, val))
    return sorted(seen.values(), key=lambda c: (c[1], c[2], c[3]))


TEMPLATE = """/* GENERATED by tests/manual/uart_scan.py - do not commit. */
#include <stdint.h>
#define R32(a) (*(volatile uint32_t *)(uintptr_t)(a))
#define R16(a) (*(volatile uint16_t *)(uintptr_t)(a))
#define RCC  0x40021000u
#define AFIO 0x40010000u
#define GPIO(p) (0x40010800u + 0x400u * (p))

struct Cand {{ uint32_t base; int16_t apb1; uint8_t port, bit;
               uint32_t rmask, rval; const char *name; }};
static const Cand cands[] = {{
{rows}
}};

static void cfg_pin(uint8_t port, uint8_t bit) {{
  R32(RCC + 0x18) |= (1u << (2 + port));
  volatile uint32_t *reg; uint32_t sh;
  if (bit < 8)       {{ reg = &R32(GPIO(port) + 0x00); sh = bit * 4u; }}
  else if (bit < 16) {{ reg = &R32(GPIO(port) + 0x04); sh = (bit - 8u) * 4u; }}
  else               {{ reg = &R32(GPIO(port) + 0x1C); sh = (bit - 16u) * 4u; }}
  *reg = (*reg & ~(0xFu << sh)) | (0xBu << sh);   /* AF push-pull 50 MHz */
}}

static void put(uint32_t base, const char *s) {{
  while (*s) {{
    while (!(R16(base + 0x00) & (1u << 7))) {{ }}
    R16(base + 0x04) = (uint16_t)(uint8_t)*s++;
  }}
  while (!(R16(base + 0x00) & (1u << 6))) {{ }}
}}

void setup() {{ }}

void loop() {{
  R32(RCC + 0x18) |= 1u;
  for (unsigned i = 0; i < sizeof(cands) / sizeof(cands[0]); i++) {{
    const Cand &c = cands[i];
    if (c.apb1 < 0) R32(RCC + 0x18) |= (1u << 14);
    else            R32(RCC + 0x1C) |= (1u << c.apb1);
    if (c.rmask) R32(AFIO + 0x04) = (R32(AFIO + 0x04) & ~c.rmask) | c.rval;
    cfg_pin(c.port, c.bit);
    R16(c.base + 0x08) = (uint16_t)((F_CPU + {half}u) / {baud}u);
    R16(c.base + 0x0C) = (1u << 13) | (1u << 3);
    for (int k = 0; k < 3; k++) {{ put(c.base, c.name); put(c.base, "\\r\\n"); }}
    R16(c.base + 0x0C) = 0;
    for (volatile uint32_t d = 0; d < F_CPU / 40u; d++) {{ }}
  }}
}}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--board", required=True)
    ap.add_argument("--pnum", default="ANY")
    ap.add_argument("--port")
    ap.add_argument("--probe")
    ap.add_argument("--baud", type=int, default=115200)
    ap.add_argument("--seconds", type=float, default=12.0)
    args = ap.parse_args()

    gcc = os.environ.get("CH32_GCC_BIN")
    tables = os.environ.get("CH32_TABLES")
    if not (gcc and tables):
        print("set CH32_GCC_BIN and CH32_TABLES", file=sys.stderr)
        return 2

    sys.path.insert(0, str(REPO / "tests" / "hardware"))
    from smoke import resolve_port, find_probe_rs

    probe_rs_dir = os.environ.get("CH32_PROBE_RS") or find_probe_rs()
    if not probe_rs_dir:
        print("probe-rs not found; set CH32_PROBE_RS", file=sys.stderr)
        return 2

    port, probe_serial = resolve_port(args.probe, args.port)
    cands = candidates(args.board, pathlib.Path(tables))
    if not cands:
        print(f"{args.board}: no selectable USART route in device-data")
        return 1
    print(f"== probe {probe_serial or '(unidentified)'} -> {port}")
    print(f"== {args.board}: trying {len(cands)} routes: "
          + ", ".join(c[0] for c in cands))

    rows = "\n".join(
        '  {{ 0x{base:08x}u, {apb1:3d}, {port}, {bit:2d}, 0x{mask:08x}u, '
        '0x{val:08x}u, "{label}" }},'.format(
            base=USART_BASE[index], apb1=APB1_BIT.get(index, -1),
            port="ABCDEF".index(pt), bit=bit, mask=mask, val=val, label=label)
        for label, index, pt, bit, mask, val in cands)
    source = TEMPLATE.format(rows=rows, baud=args.baud, half=args.baud // 2)

    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        sketch = tmp / "UartScan"
        sketch.mkdir()
        (sketch / "UartScan.ino").write_text(source, encoding="utf-8")
        (tmp / "user" / "hardware" / "ch32-riscv-ug").mkdir(parents=True)
        (tmp / "user" / "hardware" / "ch32-riscv-ug" / "ch32v").symlink_to(REPO)
        env = dict(os.environ, ARDUINO_DIRECTORIES_USER=str(tmp / "user"))
        r = subprocess.run(
            ["arduino-cli", "compile",
             "--fqbn", f"ch32-riscv-ug:ch32v:{args.board}:pnum={args.pnum}",
             "--build-property", f"compiler.path={gcc}/",
             "--build-path", str(tmp / "build"), str(sketch)],
            env=env, capture_output=True, text=True)
        if r.returncode:
            print(r.stdout + r.stderr)
            return 1
        upload = ["arduino-cli", "upload",
                  "--fqbn", f"ch32-riscv-ug:ch32v:{args.board}:pnum={args.pnum}",
                  "--programmer", "wch-link", "--input-dir", str(tmp / "build"),
                  "--upload-property", f"runtime.tools.probe-rs.path={probe_rs_dir}"]
        if probe_serial and args.probe:
            upload += ["--upload-property",
                       f"upload.probe_args=--probe 1a86:8010:{probe_serial}"]
        upload.append(str(sketch))

        import serial
        with serial.Serial(port, args.baud, timeout=0.3) as uart:
            uart.reset_input_buffer()
            r = subprocess.run(upload, env=env, capture_output=True, text=True)
            if r.returncode:
                print(r.stdout + r.stderr)
                return 1
            deadline = time.time() + args.seconds
            got = b""
            while time.time() < deadline:
                got += uart.read(256)

    text = got.decode(errors="replace")
    hits = [c[0] for c in cands if c[0] in text]
    print("--- output " + "-" * 48)
    print(text.strip() or "(nothing received)")
    print("-" * 59)
    if hits:
        print(f"WIRED: {', '.join(hits)}")
        return 0
    print("no route reached the host: the board's UART is not connected to the "
          "probe's bridge, or it uses a route device-data cannot select")
    return 1


if __name__ == "__main__":
    sys.exit(main())
