/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: ch32-device-data tables @ git 8c09ab446f510a1ab056dad4c7f3ae5fbdc91ad9
 *
 * PLACEHOLDER. This is not a pin map: no pad is mapped to an Arduino
 * pin number yet. Generated from device-data only so the variant
 * compiles. Replaced once Q-011 fixes the pin numbering scheme. */
#pragma once

#define CH32_VARIANT_CH32V006 1
#define NUM_DIGITAL_PINS 31
#define LED_BUILTIN 0
