/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: ch32-device-data tables @ git 8c09ab446f510a1ab056dad4c7f3ae5fbdc91ad9
 *
 * CH32V006 pin map: the union of all 7 part numbers in the
 * series, so the same header serves the ANY menu entry and every SKU.
 *
 * Pin numbers are port-encoded (ADR-0010): pin = (port << 5) | bit.
 * The valid set is SPARSE. NUM_DIGITAL_PINS is one past the highest pin
 * number, NOT a pad count, and 0..NUM_DIGITAL_PINS-1 is not a usable
 * loop range - test with digitalPinIsValid(pin).
 *
 * A pad missing from a given package is left unbonded: writing it only
 * touches a register bit with nothing attached, which is harmless.
 */
#pragma once

#include "ch32_pins.h"

#define CH32_VARIANT_CH32V006 1

/* ---- GPIO pads: 31 in the series, 8 of them on every part ---- */
#define PA0 CH32_PIN(0,  0)
#define PA1 CH32_PIN(0,  1)
#define PA2 CH32_PIN(0,  2)
#define PA3 CH32_PIN(0,  3)
#define PA4 CH32_PIN(0,  4)
#define PA5 CH32_PIN(0,  5)
#define PA6 CH32_PIN(0,  6)
#define PA7 CH32_PIN(0,  7)
#define PB0 CH32_PIN(1,  0)
#define PB1 CH32_PIN(1,  1)
#define PB2 CH32_PIN(1,  2)
#define PB3 CH32_PIN(1,  3)
#define PB4 CH32_PIN(1,  4)
#define PB5 CH32_PIN(1,  5)
#define PB6 CH32_PIN(1,  6)
#define PC0 CH32_PIN(2,  0)
#define PC1 CH32_PIN(2,  1)
#define PC2 CH32_PIN(2,  2)
#define PC3 CH32_PIN(2,  3)
#define PC4 CH32_PIN(2,  4)
#define PC5 CH32_PIN(2,  5)
#define PC6 CH32_PIN(2,  6)
#define PC7 CH32_PIN(2,  7)
#define PD0 CH32_PIN(3,  0)
#define PD1 CH32_PIN(3,  1)
#define PD2 CH32_PIN(3,  2)
#define PD3 CH32_PIN(3,  3)
#define PD4 CH32_PIN(3,  4)
#define PD5 CH32_PIN(3,  5)
#define PD6 CH32_PIN(3,  6)
#define PD7 CH32_PIN(3,  7)

/* Bit n set = P<port>n is bonded out on at least one part in the series. */
#define CH32_PORT_MASK_A 0x000000ffu
#define CH32_PORT_MASK_B 0x0000007fu
#define CH32_PORT_MASK_C 0x000000ffu
#define CH32_PORT_MASK_D 0x000000ffu
#define CH32_PORT_MASK_E 0x00000000u   /* port absent */
#define CH32_PORT_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_MASK(port) ( \
    (port) == 0 ? CH32_PORT_MASK_A : \
    (port) == 1 ? CH32_PORT_MASK_B : \
    (port) == 2 ? CH32_PORT_MASK_C : \
    (port) == 3 ? CH32_PORT_MASK_D : \
    (port) == 4 ? CH32_PORT_MASK_E : \
    (port) == 5 ? CH32_PORT_MASK_F : \
    0u)

/* Bit n set = P<port>n is bonded out on EVERY part in the series,
 * i.e. the pins a sketch built for the ANY menu entry can rely on. */
#define CH32_PORT_COMMON_MASK_A 0x00000006u
#define CH32_PORT_COMMON_MASK_B 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_C 0x00000011u
#define CH32_PORT_COMMON_MASK_D 0x00000093u
#define CH32_PORT_COMMON_MASK_E 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK(port) ( \
    (port) == 0 ? CH32_PORT_COMMON_MASK_A : \
    (port) == 1 ? CH32_PORT_COMMON_MASK_B : \
    (port) == 2 ? CH32_PORT_COMMON_MASK_C : \
    (port) == 3 ? CH32_PORT_COMMON_MASK_D : \
    (port) == 4 ? CH32_PORT_COMMON_MASK_E : \
    (port) == 5 ? CH32_PORT_COMMON_MASK_F : \
    0u)

#define NUM_DIGITAL_PINS 104   /* highest pin number + 1, not a pad count */
#define PINS_COUNT       NUM_DIGITAL_PINS
#define CH32_GPIO_COUNT  31   /* actual pads in the series */

/* ---- ADC1 analog inputs (8 channels) ---- */
#define NUM_ANALOG_INPUTS 8
#define A0   PA2
#define A1   PA1
#define A2   PC4
#define A3   PD2
#define A4   PD3
#define A5   PD5
#define A6   PD6
#define A7   PD4
#define CH32_PIN_TO_ADC_CHANNEL(p) ( \
    (p) == PA2 ? 0 : \
    (p) == PA1 ? 1 : \
    (p) == PC4 ? 2 : \
    (p) == PD2 ? 3 : \
    (p) == PD3 ? 4 : \
    (p) == PD5 ? 5 : \
    (p) == PD6 ? 6 : \
    (p) == PD4 ? 7 : \
    NOT_AN_ANALOG_PIN)
#define CH32_ADC_CHANNEL_TO_PIN(c) ( \
    (c) == 0 ? PA2 : \
    (c) == 1 ? PA1 : \
    (c) == 2 ? PC4 : \
    (c) == 3 ? PD2 : \
    (c) == 4 ? PD3 : \
    (c) == 5 ? PD5 : \
    (c) == 6 ? PD6 : \
    (c) == 7 ? PD4 : \
    NOT_A_PIN)

/* ---- USART pins (device-data; one route per USART, chosen for
 *      the whole series - see choose_uarts in generate.py) ---- */
/* USART1: route default, on 6 of 7 parts */
#define CH32_SERIAL1_TX PD5
#define CH32_SERIAL1_RX PD6
#define CH32_SERIAL1_HANDLER USART1_IRQHandler
#define CH32_SERIAL1_IRQ CH32_IRQN_USART1
/* USART2: route default, on 1 of 7 parts */
#define CH32_SERIAL2_TX PA7
#define CH32_SERIAL2_RX PB3
#define CH32_SERIAL2_HANDLER USART2_IRQHandler
#define CH32_SERIAL2_IRQ CH32_IRQN_USART2
#ifndef CH32_SERIAL_DEFAULT
#define CH32_SERIAL_DEFAULT 1
#endif

/* ---- PWM: 7 pads on TIM1/TIM2/TIM3, default route ---- */
#define CH32_PWM_PIN_COUNT 7
#define CH32_PWM_PIN_TO_TIMER(p) ( \
    (p) == PD2 ? 1 : \
    (p) == PA1 ? 1 : \
    (p) == PC3 ? 1 : \
    (p) == PC4 ? 1 : \
    (p) == PD3 ? 2 : \
    (p) == PC0 ? 2 : \
    (p) == PD7 ? 2 : \
    0)
#define CH32_PWM_PIN_TO_CHANNEL(p) ( \
    (p) == PD2 ? 1 : \
    (p) == PA1 ? 2 : \
    (p) == PC3 ? 3 : \
    (p) == PC4 ? 4 : \
    (p) == PD3 ? 2 : \
    (p) == PC0 ? 3 : \
    (p) == PD7 ? 4 : \
    0)

/* Generic boards have no on-board LED. This placeholder only exists so
 * that the stock examples compile; it is the lowest-numbered pad present
 * on every part in the series. Override it per board or on the command
 * line: --build-property build.extra_flags=-DLED_BUILTIN=PC13 */
#ifndef LED_BUILTIN
#define LED_BUILTIN PA1
#endif
