#!/usr/bin/env -S uv run --no-project --script
# /// script
# requires-python = ">=3.10"
# ///
"""Regenerate the `profiles:` block of every sketch.yaml in the repository.

Two trees, because both need the same board list and must not drift apart:

  tests/sketches/**/         the HIL cases. Keep their hand-written header
                             comment; only the profiles block is generated.
  libraries/*/examples/*/    the bundled examples. Generated in full - they
                             have nothing hand-written to keep, since what a
                             sketch requires is declared in its own .ino
                             (see tests/sketch_requirements.py). They ship to
                             users, so `arduino-cli compile --profile
                             ch32v003` works on a downloaded example.

A profile is a board, and every sketch needs the same set of them. Written by
hand that is 24 boards x N sketches of copy-paste that silently drifts (the
first two sketches already disagreed about which boards exist). The board list
lives here instead, and each sketch.yaml keeps only its own header comment.

  uv run tests/sketches/sync_profiles.py           # rewrite
  uv run tests/sketches/sync_profiles.py --check   # CI: fail if out of date

Tiers come from ../TEST_PLAN.ja.md. Only tier A and B boards get a profile:
a profile is a promise that someone runs it on hardware, and an unrunnable
profile is worse than no profile. Everything else is covered by the compile
matrix (tests/compile), which needs no profile.

A sketch that cannot fit every tier A/B board declares its floor in
REQUIREMENTS; boards below it are left out of that sketch's profile list rather
than shipped as a profile that fails to link. The `ANY` menu entry's limits are
what matter, because that is what the profiles use - it is the smallest part in
the series.
"""
import argparse
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO / "tests"))

from sketch_requirements import requirements, unmet   # noqa: E402
INDEX_URL = ("https://ch32-riscv-ug.github.io/ArduinoCore-CH32/"
             "package_ch32-riscv-ug_index.json")
PLATFORM = "ch32-riscv-ug:ch32v (0.0.1)"

# (profile name, board id, tier, note). Keep in sync with docs/TEST_PLAN.ja.md.
BOARDS = [
    ("ch32x035", "CH32X035", "A", "main target; 24-bit ports, 48 MHz, 2 wait states"),
    ("ch32v003", "CH32V003", "A", "the other extreme: rv32ec, 24 MHz, 16 K flash"),
    ("ch32v203", "CH32V203", "B", "the mainstream V2 part"),
    ("ch32l103", "CH32L103", "B", "low-power V4C"),
    ("ch32v103", "CH32V103", "B", "the only family with a jump-table vector"),
    ("ch32v307", "CH32V307", "B", "largest part on the bench"),
]

# Sketch directory name -> what the board must have for it to link, in bytes of
# (flash, RAM). Sketches absent from here run everywhere.
# Nothing needs an entry right now: since ADR-0004's --specs=nano.specs went in,
# every sketch here fits CH32V003's 16 KB / 2 KB. It did not before - the full
# newlib formatter alone is ~40 KB and its malloc arena overflowed the 2 KB of
# RAM - so the mechanism stays, and compile_all.py is what proves the claim.
REQUIREMENTS = {}

MARK_BEGIN = "# --- generated by sync_profiles.py: do not edit below ---"
MARK_END = "# --- end generated ---"


def limits(board: str) -> tuple:
    """(flash, RAM) of the board's ANY menu entry, from the generated boards.txt."""
    text = (REPO / "boards.txt").read_text(encoding="utf-8")
    out = {}
    for key, field in (("upload.maximum_size", "flash"),
                       ("upload.maximum_data_size", "ram")):
        marker = f"{board}.menu.pnum.ANY.{key}="
        for line in text.splitlines():
            if line.startswith(marker):
                out[field] = int(line[len(marker):])
    return out.get("flash", 0), out.get("ram", 0)


def block(src: pathlib.Path) -> str:
    """The generated profiles section for the sketch in `src`.

    What the sketch needs comes from its own .ino; REQUIREMENTS below is the
    older, central way of saying the same thing and still wins where it is set.
    A board that cannot meet the requirement is left out with the reason
    written in, so the omission is readable in the file itself.
    """
    need = requirements(src)
    need_flash, need_ram = REQUIREMENTS.get(src.name, (0, 0))
    need = {"caps": need["caps"],
            "flash": max(need["flash"], need_flash),
            "ram": max(need["ram"], need_ram)}
    lines = [MARK_BEGIN, "profiles:"]
    kept = []
    for name, board, tier, note in BOARDS:
        reason = unmet(need, board)
        if reason:
            lines.append(f"  # tier {tier} {board}: omitted, {reason}")
            continue
        kept.append(name)
        lines += [
            f"  # tier {tier}: {note}",
            f"  {name}:",
            f"    fqbn: ch32-riscv-ug:ch32v:{board}:pnum=ANY",
            "    programmer: wch-link",
            "    platforms:",
            f"      - platform: {PLATFORM}",
            f"        platform_index_url: {INDEX_URL}",
            "",
        ]
    if not kept:
        raise SystemExit(f"{src.name}: its requirements leave no tier A/B board "
                         f"to run on. A sketch nobody can run is not a sketch "
                         f"to ship a profile for.")
    lines += [f"default_profile: {kept[0]}", MARK_END, ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    stale = []

    # tests/sketches: a hand-written header comment, then the generated block.
    for path in sorted(HERE.rglob("sketch.yaml")):
        generated = block(path.parent)
        text = path.read_text(encoding="utf-8")
        if MARK_BEGIN in text:
            head = text.split(MARK_BEGIN)[0]
        else:
            # First run: keep the comment header, drop the hand-written profiles.
            head = re.split(r"^profiles:", text, maxsplit=1, flags=re.M)[0]
        want = head.rstrip("\n") + "\n\n" + generated
        if want == text:
            continue
        stale.append(path.relative_to(REPO))
        if not args.check:
            path.write_text(want, encoding="utf-8")

    # libraries/*/examples: generated in full, and created if absent. A missing
    # one is not "no profiles", it is an example nobody can build by profile.
    for ino in sorted((REPO / "libraries").glob("*/examples/*/*.ino")):
        if ino.stem != ino.parent.name:
            continue          # tests/compile/test_examples.py reports this
        path = ino.parent / "sketch.yaml"
        want = (f"# Generated by tests/sketches/sync_profiles.py - do not edit.\n"
                f"# What this example requires is declared in {ino.name};\n"
                f"# see docs/examples-build-rules.ja.md.\n\n"
                + block(ino.parent))
        if path.exists() and path.read_text(encoding="utf-8") == want:
            continue
        stale.append(path.relative_to(REPO))
        if not args.check:
            path.write_text(want, encoding="utf-8")

    if args.check and stale:
        print("out of date, run tests/sketches/sync_profiles.py:", file=sys.stderr)
        for p in stale:
            print(f"  {p}", file=sys.stderr)
        return 1
    print(f"{'stale' if args.check else 'updated'}: {len(stale)} sketch.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
