#!/usr/bin/env -S uv run --no-project --script
# /// script
# requires-python = ">=3.10"
# ///
"""Regenerate the `profiles:` block of every tests/sketches/**/sketch.yaml.

A profile is a board, and every sketch needs the same set of them. Written by
hand that is 24 boards x N sketches of copy-paste that silently drifts (the
first two sketches already disagreed about which boards exist). The board list
lives here instead, and each sketch.yaml keeps only its own header comment.

  uv run tests/sketches/sync_profiles.py           # rewrite
  uv run tests/sketches/sync_profiles.py --check   # CI: fail if out of date

Tiers come from ../TEST_PLAN.ja.md. Only tier A and B boards get a profile:
a profile is a promise that someone runs it on hardware, and an unrunnable
profile is worse than no profile. Everything else is covered by the compile
matrix (tests/compile), which needs no profile.

A sketch that cannot fit every tier A/B board declares its floor in
REQUIREMENTS; boards below it are left out of that sketch's profile list rather
than shipped as a profile that fails to link. The `ANY` menu entry's limits are
what matter, because that is what the profiles use - it is the smallest part in
the series.
"""
import argparse
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]
INDEX_URL = ("https://ch32-riscv-ug.github.io/ArduinoCore-CH32/"
             "package_ch32-riscv-ug_index.json")
PLATFORM = "ch32-riscv-ug:ch32v (0.0.1)"

# (profile name, board id, tier, note). Keep in sync with docs/TEST_PLAN.ja.md.
BOARDS = [
    ("ch32x035", "CH32X035", "A", "main target; 24-bit ports, 48 MHz, 2 wait states"),
    ("ch32v003", "CH32V003", "A", "the other extreme: rv32ec, 24 MHz, 16 K flash"),
    ("ch32v203", "CH32V203", "B", "the mainstream V2 part"),
    ("ch32l103", "CH32L103", "B", "low-power V4C"),
    ("ch32v103", "CH32V103", "B", "the only family with a jump-table vector"),
    ("ch32v307", "CH32V307", "B", "largest part on the bench"),
]

# Sketch directory name -> what the board must have for it to link, in bytes of
# (flash, RAM). Sketches absent from here run everywhere.
# Nothing needs an entry right now: since ADR-0004's --specs=nano.specs went in,
# every sketch here fits CH32V003's 16 KB / 2 KB. It did not before - the full
# newlib formatter alone is ~40 KB and its malloc arena overflowed the 2 KB of
# RAM - so the mechanism stays, and compile_all.sh is what proves the claim.
REQUIREMENTS = {}

MARK_BEGIN = "# --- generated by sync_profiles.py: do not edit below ---"
MARK_END = "# --- end generated ---"


def limits(board: str) -> tuple:
    """(flash, RAM) of the board's ANY menu entry, from the generated boards.txt."""
    text = (REPO / "boards.txt").read_text(encoding="utf-8")
    out = {}
    for key, field in (("upload.maximum_size", "flash"),
                       ("upload.maximum_data_size", "ram")):
        marker = f"{board}.menu.pnum.ANY.{key}="
        for line in text.splitlines():
            if line.startswith(marker):
                out[field] = int(line[len(marker):])
    return out.get("flash", 0), out.get("ram", 0)


def block(sketch: str) -> str:
    need_flash, need_ram = REQUIREMENTS.get(sketch, (0, 0))
    lines = [MARK_BEGIN, "profiles:"]
    kept = []
    for name, board, tier, note in BOARDS:
        flash, ram = limits(board)
        if flash < need_flash or ram < need_ram:
            lines.append(f"  # tier {tier} {board}: omitted, needs "
                         f"{need_flash // 1024} KB flash / {need_ram // 1024} KB RAM")
            continue
        kept.append(name)
        lines += [
            f"  # tier {tier}: {note}",
            f"  {name}:",
            f"    fqbn: ch32-riscv-ug:ch32v:{board}:pnum=ANY",
            "    programmer: wch-link",
            "    platforms:",
            f"      - platform: {PLATFORM}",
            f"        platform_index_url: {INDEX_URL}",
            "",
        ]
    if not kept:
        raise SystemExit(f"{sketch}: REQUIREMENTS leave no board to run on")
    lines += [f"default_profile: {kept[0]}", MARK_END, ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    stale = []
    for path in sorted(HERE.rglob("sketch.yaml")):
        generated = block(path.parent.name)
        text = path.read_text(encoding="utf-8")
        if MARK_BEGIN in text:
            head = text.split(MARK_BEGIN)[0]
        else:
            # First run: keep the comment header, drop the hand-written profiles.
            head = re.split(r"^profiles:", text, maxsplit=1, flags=re.M)[0]
        want = head.rstrip("\n") + "\n\n" + generated
        if want == text:
            continue
        stale.append(path.relative_to(REPO))
        if not args.check:
            path.write_text(want, encoding="utf-8")

    if args.check and stale:
        print("out of date, run tests/sketches/sync_profiles.py:", file=sys.stderr)
        for p in stale:
            print(f"  {p}", file=sys.stderr)
        return 1
    print(f"{'stale' if args.check else 'updated'}: {len(stale)} sketch.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
