#!/usr/bin/env python3
"""W-4 prototype generator: boards.txt and linker scripts from ch32-device-data tables.

Reads the normalized CSV tables (products.csv) and writes, per configured family:
  - boards.txt            (board entry + menu.pnum entry per part number)
  - variants/<VARIANT>/<ld>  (one MEMORY script per unique flash/sram combination)

Design rules (see docs/research/board-variants-and-menus.ja.md):
  - one board per mirror family, menu.pnum lists every part number
  - deterministic ordering: canonical series order, then part number
  - generated files carry a DO-NOT-EDIT header with the source repo commit
  - no timestamps in output so regeneration is idempotent (CI check mode)

Usage:
  generate.py --tables <ch32-device-data>/tables --platform <platform dir> [--check]
"""
import argparse
import csv
import pathlib
import subprocess
import sys

# Per-family generation config. Values come from verified research:
# march/mabi and startup CSR defines: docs/research/startup-files.ja.md (R-01),
# experiments 0001/0002. Only families proven by the equivalence harness are listed.
FAMILY_CONFIG = {
    "CH32V006": {
        "board_id": "CH32V00X",
        "board_name": "CH32V00X (V002/V004/V005/V006/V007/M007)",
        "variant": "CH32V00X",
        "march": "rv32emc_zicsr",
        "mabi": "ilp32e",
        "f_cpu": "48000000L",
        "startup_defines": "-DCH32_VECTORS=vectors_ch32v00x.inc "
                           "-DCH32_MSTATUS_INIT=0x1880 -DCH32_INTSYSCR_INIT=0x3",
        "ld_prefix": "ch32v00x",
        # vendor device-select macro (ch32v00X.h) per series
        "device_macro": {
            "CH32V002": "CH32V002", "CH32V004": "CH32V004", "CH32V005": "CH32V005",
            "CH32V006": "CH32V006", "CH32V007": "CH32V007_M007", "CH32M007": "CH32V007_M007",
        },
        "series_order": ["CH32V002", "CH32V004", "CH32V005",
                         "CH32V006", "CH32V007", "CH32M007"],
    },
}

MENU_HEADER = "menu.pnum=Part Number\n"


def source_commit(tables_dir: pathlib.Path) -> str:
    try:
        out = subprocess.run(["git", "-C", str(tables_dir), "rev-parse", "HEAD"],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except Exception:
        return "unknown"


def gen_header(commit: str) -> str:
    return ("# DO NOT EDIT - machine generated by tools/generate/generate.py\n"
            "# source: ch32-device-data tables @ git " + commit + "\n"
            "# Regenerate: generate.py --tables <ch32-device-data>/tables "
            "--platform <platform dir>\n")


def ld_header(commit: str) -> str:
    return ("/* DO NOT EDIT - machine generated by tools/generate/generate.py\n"
            " * source: ch32-device-data tables @ git " + commit + " */\n")


def kb(n: int) -> str:
    return str(n // 1024)


def gen_family(family: str, rows: list, commit: str):
    cfg = FAMILY_CONFIG[family]
    order = {s: i for i, s in enumerate(cfg["series_order"])}
    rows = sorted(rows, key=lambda r: (order.get(r["series"], 99), r["part_number"]))

    board = cfg["board_id"]
    lines = [gen_header(commit), MENU_HEADER, ""]
    lines.append(f"{board}.name={cfg['board_name']}")
    lines.append(f"{board}.build.board={board}")
    lines.append(f"{board}.build.core=arduino")
    lines.append(f"{board}.build.variant={cfg['variant']}")
    lines.append(f"{board}.build.march={cfg['march']}")
    lines.append(f"{board}.build.mabi={cfg['mabi']}")
    lines.append(f"{board}.build.f_cpu={cfg['f_cpu']}")
    lines.append(f"{board}.build.startup_defines={cfg['startup_defines']}")
    lines.append("")

    ld_files = {}
    for r in rows:
        pn = r["part_number"]
        flash, sram = int(r["flash_bytes"]), int(r["sram_bytes"])
        ld_name = f"{cfg['ld_prefix']}_{kb(flash)}k_{kb(sram)}k.ld"
        if ld_name not in ld_files:
            ld_files[ld_name] = (
                ld_header(commit)
                + f"/* FLASH {kb(flash)}K, SRAM {kb(sram)}K */\n"
                + "ENTRY( _start )\n\nMEMORY\n{\n"
                + f"    FLASH (rx) : ORIGIN = 0x00000000, LENGTH = {flash}\n"
                + f"    RAM (xrw)  : ORIGIN = 0x20000000, LENGTH = {sram}\n"
                + "}\n\nINCLUDE sections.ld\n")
        label = f"{pn} ({r['package']}, {kb(flash)}K/{kb(sram)}K)"
        p = f"{board}.menu.pnum.{pn}"
        lines.append(f"{p}={label}")
        lines.append(f"{p}.build.board={pn}")
        lines.append(f"{p}.build.series={cfg['device_macro'][r['series']]}")
        lines.append(f"{p}.build.ldscript={ld_name}")
        lines.append(f"{p}.upload.maximum_size={flash}")
        lines.append(f"{p}.upload.maximum_data_size={sram}")
        lines.append("")

    return "\n".join(lines), ld_files


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tables", required=True, type=pathlib.Path)
    ap.add_argument("--platform", required=True, type=pathlib.Path)
    ap.add_argument("--check", action="store_true",
                    help="verify committed files match regeneration; do not write")
    args = ap.parse_args()

    with open(args.tables / "products.csv", newline="", encoding="utf-8") as f:
        products = list(csv.DictReader(f))
    commit = source_commit(args.tables)

    outputs = {}
    for family, cfg in FAMILY_CONFIG.items():
        rows = [r for r in products if r["family"] == family]
        if not rows:
            print(f"ERROR: no products for family {family}", file=sys.stderr)
            return 1
        boards_txt, ld_files = gen_family(family, rows, commit)
        outputs[args.platform / "boards.txt"] = boards_txt
        for name, content in ld_files.items():
            outputs[args.platform / "variants" / cfg["variant"] / name] = content

    drift = 0
    for path, content in outputs.items():
        if args.check:
            on_disk = path.read_text(encoding="utf-8") if path.exists() else None
            if on_disk != content:
                print(f"DRIFT: {path}")
                drift = 1
            else:
                print(f"ok:    {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote: {path}")
    return drift


if __name__ == "__main__":
    sys.exit(main())
