#!/usr/bin/env python3
"""Generate bundled example profiles without a test harness or connected board."""
import argparse
import pathlib
import re
import sys

from sketch_requirements import all_boards, requirements, series_capabilities, unmet

REPO = pathlib.Path(__file__).resolve().parents[2]
INDEX_URL = ("https://ch32-riscv-ug.github.io/ArduinoCore-CH32RV/"
             "package_ch32-riscv-ug_index.json")
# Preserve the existing example profile selection independently of bench state.
PROFILE_BOARDS = ("CH32X035", "CH32V003", "CH32V203", "CH32L103",
                  "CH32V103", "CH32V307", "CH32V006")


def render(source: pathlib.Path) -> str:
    version = re.search(r"^version=(.+)$", (REPO / "platform.txt").read_text(),
                        re.M).group(1).strip()
    need = requirements(source)
    known = set(all_boards()) & set(series_capabilities())
    if set(PROFILE_BOARDS) - known:
        raise ValueError("Example profile references an undefined generic board")
    generic_boards = PROFILE_BOARDS
    lines = [
        "# Generated by tools/generate/sync_example_profiles.py - do not edit.",
        f"# What this example requires is declared in {source.name}.ino;",
        "# see docs/examples-build-rules.ja.md.",
        "",
        "profiles:",
    ]
    kept = []
    for board in generic_boards:
        reason = unmet(need, board)
        if reason:
            lines.append(f"  # {board}: omitted, {reason}")
            continue
        name = board.lower()
        kept.append(name)
        lines.extend([
            f"  {name}:",
            f"    fqbn: ch32-riscv-ug:ch32rv:{board}:pnum=ANY",
            "    platforms:",
            f"      - platform: ch32-riscv-ug:ch32rv ({version})",
            f"        platform_index_url: {INDEX_URL}",
            "",
        ])
    if not kept:
        raise ValueError(f"{source}: no generic board satisfies requirements")
    default = "ch32x035" if "ch32x035" in kept else kept[0]
    lines.extend([f"default_profile: {default}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for ino in sorted((REPO / "libraries").glob("*/examples/*/*.ino")):
        if ino.stem != ino.parent.name:
            continue
        destination = ino.parent / "sketch.yaml"
        wanted = render(ino.parent)
        if destination.is_file() and destination.read_text() == wanted:
            continue
        stale.append(str(destination.relative_to(REPO)))
        if not args.check:
            destination.write_text(wanted)
    if args.check and stale:
        print("Profiles differ; run tools/generate/sync_example_profiles.py:",
              file=sys.stderr)
        print("\n".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
