/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: ch32-riscv-ug/ch32-device-data tables, pinned in vendor/ch32-device-data.lock.toml
 *
 * CH32M103 pin map: the union of all 1 part numbers in the
 * series, so the same header serves the ANY menu entry and every SKU.
 *
 * Pin numbers are port-encoded (ADR-0010): pin = (port << 5) | bit.
 * The valid set is SPARSE. NUM_DIGITAL_PINS is one past the highest pin
 * number, NOT a pad count, and 0..NUM_DIGITAL_PINS-1 is not a usable
 * loop range - test with digitalPinIsValid(pin).
 *
 * A pad missing from a given package is left unbonded: writing it only
 * touches a register bit with nothing attached, which is harmless.
 */
#pragma once

#include "ch32_pins.h"

#define CH32_VARIANT_CH32M103 1

/* ---- peripheral clock enables (clock_enables.csv) ----
 * The RCC register that turns each block on, and the bit. Per family,
 * because it differs: CH32V006 has USART2 on the APB2 register at bit 13
 * where the F1-style parts have it on APB1 bit 17. Use through
 * ch32_clock_enable(NAME) / ch32_clock_disable(NAME). ---- */
#define CH32_CLKEN_ADC1_ADDR 0x40021018u
#define CH32_CLKEN_ADC1_MASK 0x00000200u
#define CH32_CLKEN_AFIO_ADDR 0x40021018u
#define CH32_CLKEN_AFIO_MASK 0x00000001u
#define CH32_CLKEN_BKP_ADDR 0x4002101cu
#define CH32_CLKEN_BKP_MASK 0x08000000u
#define CH32_CLKEN_CAN1_ADDR 0x4002101cu
#define CH32_CLKEN_CAN1_MASK 0x02000000u
#define CH32_CLKEN_CRC_ADDR 0x40021014u
#define CH32_CLKEN_CRC_MASK 0x00000040u
#define CH32_CLKEN_DMA1_ADDR 0x40021014u
#define CH32_CLKEN_DMA1_MASK 0x00000001u
#define CH32_CLKEN_GPIOA_ADDR 0x40021018u
#define CH32_CLKEN_GPIOA_MASK 0x00000004u
#define CH32_CLKEN_GPIOB_ADDR 0x40021018u
#define CH32_CLKEN_GPIOB_MASK 0x00000008u
#define CH32_CLKEN_GPIOC_ADDR 0x40021018u
#define CH32_CLKEN_GPIOC_MASK 0x00000010u
#define CH32_CLKEN_GPIOD_ADDR 0x40021018u
#define CH32_CLKEN_GPIOD_MASK 0x00000020u
#define CH32_CLKEN_I2C1_ADDR 0x4002101cu
#define CH32_CLKEN_I2C1_MASK 0x00200000u
#define CH32_CLKEN_I2C2_ADDR 0x4002101cu
#define CH32_CLKEN_I2C2_MASK 0x00400000u
#define CH32_CLKEN_LPTIM_ADDR 0x4002101cu
#define CH32_CLKEN_LPTIM_MASK 0x80000000u
#define CH32_CLKEN_PWR_ADDR 0x4002101cu
#define CH32_CLKEN_PWR_MASK 0x10000000u
#define CH32_CLKEN_SPI1_ADDR 0x40021018u
#define CH32_CLKEN_SPI1_MASK 0x00001000u
#define CH32_CLKEN_SPI2_ADDR 0x4002101cu
#define CH32_CLKEN_SPI2_MASK 0x00004000u
#define CH32_CLKEN_SRAM_ADDR 0x40021014u
#define CH32_CLKEN_SRAM_MASK 0x00000004u
#define CH32_CLKEN_TIM1_ADDR 0x40021018u
#define CH32_CLKEN_TIM1_MASK 0x00000800u
#define CH32_CLKEN_TIM2_ADDR 0x4002101cu
#define CH32_CLKEN_TIM2_MASK 0x00000001u
#define CH32_CLKEN_TIM3_ADDR 0x4002101cu
#define CH32_CLKEN_TIM3_MASK 0x00000002u
#define CH32_CLKEN_TIM4_ADDR 0x4002101cu
#define CH32_CLKEN_TIM4_MASK 0x00000004u
#define CH32_CLKEN_USART1_ADDR 0x40021018u
#define CH32_CLKEN_USART1_MASK 0x00004000u
#define CH32_CLKEN_USART2_ADDR 0x4002101cu
#define CH32_CLKEN_USART2_MASK 0x00020000u
#define CH32_CLKEN_USART3_ADDR 0x4002101cu
#define CH32_CLKEN_USART3_MASK 0x00040000u
#define CH32_CLKEN_USART4_ADDR 0x4002101cu
#define CH32_CLKEN_USART4_MASK 0x00080000u
#define CH32_CLKEN_USBFS_ADDR 0x40021014u
#define CH32_CLKEN_USBFS_MASK 0x00001000u
#define CH32_CLKEN_USBPD_ADDR 0x40021014u
#define CH32_CLKEN_USBPD_MASK 0x00020000u
#define CH32_CLKEN_WWDG_ADDR 0x4002101cu
#define CH32_CLKEN_WWDG_MASK 0x00000800u
/* The ports share one register, PA at _BIT0 and the rest contiguous. */
#define CH32_CLKEN_GPIO_ADDR 0x40021018u
#define CH32_CLKEN_GPIO_BIT0 2

/* ---- GPIO pads: 21 in the series, 21 of them on every part ---- */
#define PA0  CH32_PIN(0,  0)
#define PA1  CH32_PIN(0,  1)
#define PA2  CH32_PIN(0,  2)
#define PA3  CH32_PIN(0,  3)
#define PA4  CH32_PIN(0,  4)
#define PA5  CH32_PIN(0,  5)
#define PA6  CH32_PIN(0,  6)
#define PA7  CH32_PIN(0,  7)
#define PA11 CH32_PIN(0, 11)
#define PA12 CH32_PIN(0, 12)
#define PA13 CH32_PIN(0, 13)
#define PA14 CH32_PIN(0, 14)
#define PB0  CH32_PIN(1,  0)
#define PB1  CH32_PIN(1,  1)
#define PB3  CH32_PIN(1,  3)
#define PB5  CH32_PIN(1,  5)
#define PB6  CH32_PIN(1,  6)
#define PB7  CH32_PIN(1,  7)
#define PB8  CH32_PIN(1,  8)
#define PB10 CH32_PIN(1, 10)
#define PB11 CH32_PIN(1, 11)

/* Bit n set = P<port>n is bonded out on at least one part in the series. */
#define CH32_PORT_MASK_A 0x000078ffu
#define CH32_PORT_MASK_B 0x00000debu
#define CH32_PORT_MASK_C 0x00000000u   /* port absent */
#define CH32_PORT_MASK_D 0x00000000u   /* port absent */
#define CH32_PORT_MASK_E 0x00000000u   /* port absent */
#define CH32_PORT_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_MASK(port) ( \
    (port) == 0 ? CH32_PORT_MASK_A : \
    (port) == 1 ? CH32_PORT_MASK_B : \
    (port) == 2 ? CH32_PORT_MASK_C : \
    (port) == 3 ? CH32_PORT_MASK_D : \
    (port) == 4 ? CH32_PORT_MASK_E : \
    (port) == 5 ? CH32_PORT_MASK_F : \
    0u)

/* Bit n set = P<port>n is bonded out on EVERY part in the series,
 * i.e. the pins a sketch built for the ANY menu entry can rely on. */
#define CH32_PORT_COMMON_MASK_A 0x000078ffu
#define CH32_PORT_COMMON_MASK_B 0x00000debu
#define CH32_PORT_COMMON_MASK_C 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_D 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_E 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK(port) ( \
    (port) == 0 ? CH32_PORT_COMMON_MASK_A : \
    (port) == 1 ? CH32_PORT_COMMON_MASK_B : \
    (port) == 2 ? CH32_PORT_COMMON_MASK_C : \
    (port) == 3 ? CH32_PORT_COMMON_MASK_D : \
    (port) == 4 ? CH32_PORT_COMMON_MASK_E : \
    (port) == 5 ? CH32_PORT_COMMON_MASK_F : \
    0u)

#define NUM_DIGITAL_PINS 44   /* highest pin number + 1, not a pad count */
#define PINS_COUNT       NUM_DIGITAL_PINS
#define CH32_GPIO_COUNT  21   /* actual pads in the series */

/* ---- ADC1 analog inputs (10 channels) ---- */
#define NUM_ANALOG_INPUTS 10
#define A0   PA0
#define A1   PA1
#define A2   PA2
#define A3   PA3
#define A4   PA4
#define A5   PA5
#define A6   PA6
#define A7   PA7
#define A8   PB0
#define A9   PB1
#define CH32_PIN_TO_ADC_CHANNEL(p) ( \
    (p) == PA0 ? 0 : \
    (p) == PA1 ? 1 : \
    (p) == PA2 ? 2 : \
    (p) == PA3 ? 3 : \
    (p) == PA4 ? 4 : \
    (p) == PA5 ? 5 : \
    (p) == PA6 ? 6 : \
    (p) == PA7 ? 7 : \
    (p) == PB0 ? 8 : \
    (p) == PB1 ? 9 : \
    NOT_AN_ANALOG_PIN)
#define CH32_ADC_CHANNEL_TO_PIN(c) ( \
    (c) == 0 ? PA0 : \
    (c) == 1 ? PA1 : \
    (c) == 2 ? PA2 : \
    (c) == 3 ? PA3 : \
    (c) == 4 ? PA4 : \
    (c) == 5 ? PA5 : \
    (c) == 6 ? PA6 : \
    (c) == 7 ? PA7 : \
    (c) == 8 ? PB0 : \
    (c) == 9 ? PB1 : \
    NOT_A_PIN)

/* ---- USART pins (device-data; one route per USART, chosen for
 *      the whole series - see choose_uarts in generate.py) ---- */
/* USART1: route remap-1, on every part */
#define CH32_SERIAL1_TX PB6
#define CH32_SERIAL1_RX PB7
#define CH32_SERIAL1_HANDLER USART1_IRQHandler
#define CH32_SERIAL1_CLKEN_ADDR 0x40021018u
#define CH32_SERIAL1_CLKEN_MASK 0x00004000u
#define CH32_SERIAL1_IRQ CH32_IRQN_USART1
#define CH32_SERIAL1_REMAP_MASK 0x00000004u
#define CH32_SERIAL1_REMAP_VAL  0x00000004u
#define CH32_SERIAL1_REMAP2_MASK 0x00180000u
#define CH32_SERIAL1_REMAP2_VAL  0x00000000u
/* SERIAL1 routes for setRoute()/setPins(): route number, then TX, RX */
#define CH32_SERIAL1_ROUTE_COUNT 1
#define CH32_SERIAL1_ROUTES { \
    { 1, { PB6, PB7, CH32_ROUTE_NO_PIN }, 0x00000004u, 0x00000000u }, \
}
/* USART2: route default, on every part */
#define CH32_SERIAL2_TX PA2
#define CH32_SERIAL2_RX PA3
#define CH32_SERIAL2_HANDLER USART2_IRQHandler
#define CH32_SERIAL2_CLKEN_ADDR 0x4002101cu
#define CH32_SERIAL2_CLKEN_MASK 0x00020000u
#define CH32_SERIAL2_IRQ CH32_IRQN_USART2
#define CH32_SERIAL2_REMAP_MASK 0x00000008u
#define CH32_SERIAL2_REMAP_VAL  0x00000000u
#define CH32_SERIAL2_REMAP2_MASK 0x00040000u
#define CH32_SERIAL2_REMAP2_VAL  0x00000000u
/* SERIAL2 routes for setRoute()/setPins(): route number, then TX, RX */
#define CH32_SERIAL2_ROUTE_COUNT 1
#define CH32_SERIAL2_ROUTES { \
    { 0, { PA2, PA3, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00000000u }, \
}
/* USART3: route default, on every part */
#define CH32_SERIAL3_TX PB10
#define CH32_SERIAL3_RX PB11
#define CH32_SERIAL3_HANDLER USART3_IRQHandler
#define CH32_SERIAL3_CLKEN_ADDR 0x4002101cu
#define CH32_SERIAL3_CLKEN_MASK 0x00040000u
#define CH32_SERIAL3_IRQ CH32_IRQN_USART3
#define CH32_SERIAL3_REMAP_MASK 0x00000030u
#define CH32_SERIAL3_REMAP_VAL  0x00000000u
/* SERIAL3 routes for setRoute()/setPins(): route number, then TX, RX */
#define CH32_SERIAL3_ROUTE_COUNT 1
#define CH32_SERIAL3_ROUTES { \
    { 0, { PB10, PB11, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00000000u }, \
}
/* USART4: route default, on every part */
#define CH32_SERIAL4_TX PB0
#define CH32_SERIAL4_RX PB1
#define CH32_SERIAL4_HANDLER USART4_IRQHandler
#define CH32_SERIAL4_CLKEN_ADDR 0x4002101cu
#define CH32_SERIAL4_CLKEN_MASK 0x00080000u
#define CH32_SERIAL4_IRQ CH32_IRQN_USART4
#define CH32_SERIAL4_REMAP2_MASK 0x00010000u
#define CH32_SERIAL4_REMAP2_VAL  0x00000000u
/* SERIAL4 routes for setRoute()/setPins(): route number, then TX, RX */
#define CH32_SERIAL4_ROUTE_COUNT 2
#define CH32_SERIAL4_ROUTES { \
    { 0, { PB0, PB1, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00000000u }, \
    { 1, { PA5, PB5, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00010000u }, \
}
#ifndef CH32_SERIAL_DEFAULT
#define CH32_SERIAL_DEFAULT 2
#endif

/* ---- I2C pins (device-data; one route per instance,
 *      chosen for the whole series - see choose_i2cs) ---- */
/* I2C1: route default, on every part */
#define CH32_I2C1_SCL PB6
#define CH32_I2C1_SDA PB7
#define CH32_I2C1_CLKEN_ADDR 0x4002101cu
#define CH32_I2C1_CLKEN_MASK 0x00200000u
#define CH32_I2C1_REMAP_MASK 0x00000002u
#define CH32_I2C1_REMAP_VAL  0x00000000u
#define CH32_I2C1_REMAP2_MASK 0x00800000u
#define CH32_I2C1_REMAP2_VAL  0x00000000u
/* I2C1 routes for setRoute()/setPins(): route number, then SCL, SDA */
#define CH32_I2C1_ROUTE_COUNT 2
#define CH32_I2C1_ROUTES { \
    { 0, { PB6, PB7, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00000000u }, \
    { 2, { PA13, PA12, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00800000u }, \
}
/* I2C2: route default, on every part */
#define CH32_I2C2_SCL PB10
#define CH32_I2C2_SDA PB11
#define CH32_I2C2_CLKEN_ADDR 0x4002101cu
#define CH32_I2C2_CLKEN_MASK 0x00400000u
/* Arduino's standard names for the first bus (Wire). */
#ifndef PIN_WIRE_SCL
#define PIN_WIRE_SCL CH32_I2C1_SCL
#define PIN_WIRE_SDA CH32_I2C1_SDA
#define SCL PIN_WIRE_SCL
#define SDA PIN_WIRE_SDA
#endif

/* ---- SPI pins (device-data; one route per instance,
 *      chosen for the whole series - see choose_spis).
 *      NSS is not listed: Arduino drives chip select as a GPIO. ---- */
/* SPI1: route default, on every part */
#define CH32_SPI1_SCK PA5
#define CH32_SPI1_MISO PA6
#define CH32_SPI1_MOSI PA7
#define CH32_SPI1_CLKEN_ADDR 0x40021018u
#define CH32_SPI1_CLKEN_MASK 0x00001000u
#define CH32_SPI1_REMAP_MASK 0x00000001u
#define CH32_SPI1_REMAP_VAL  0x00000000u
#define CH32_SPI1_REMAP2_MASK 0x01000000u
#define CH32_SPI1_REMAP2_VAL  0x00000000u
/* SPI1 routes for setRoute()/setPins(): route number, then SCK, MISO, MOSI */
#define CH32_SPI1_ROUTE_COUNT 3
#define CH32_SPI1_ROUTES { \
    { 0, { PA5, PA6, PA7 }, 0x00000000u, 0x00000000u }, \
    { 2, { PB6, PB8, PB7 }, 0x00000000u, 0x01000000u }, \
    { 3, { PB6, PB8, PB7 }, 0x00000001u, 0x01000000u }, \
}
/* Arduino's standard names for the first bus (SPI). */
#ifndef PIN_SPI_SCK
#define PIN_SPI_SCK CH32_SPI1_SCK
#define PIN_SPI_MISO CH32_SPI1_MISO
#define PIN_SPI_MOSI CH32_SPI1_MOSI
#define SCK PIN_SPI_SCK
#define MISO PIN_SPI_MISO
#define MOSI PIN_SPI_MOSI
#define PIN_SPI_SS PA4
#define SS PIN_SPI_SS
#endif

/* ---- PWM: 8 pads on TIM1/TIM2/TIM3, default route ---- */
#define CH32_PWM_PIN_COUNT 8
#define CH32_PWM_PIN_TO_TIMER(p) ( \
    (p) == PA11 ? 1 : \
    (p) == PA1 ? 2 : \
    (p) == PA2 ? 2 : \
    (p) == PA3 ? 2 : \
    (p) == PA6 ? 3 : \
    (p) == PA7 ? 3 : \
    (p) == PB0 ? 3 : \
    (p) == PB1 ? 3 : \
    0)
#define CH32_PWM_PIN_TO_CHANNEL(p) ( \
    (p) == PA11 ? 4 : \
    (p) == PA1 ? 2 : \
    (p) == PA2 ? 3 : \
    (p) == PA3 ? 4 : \
    (p) == PA6 ? 1 : \
    (p) == PA7 ? 2 : \
    (p) == PB0 ? 3 : \
    (p) == PB1 ? 4 : \
    0)

/* ---- tone(): TIM4, free of PWM pads. ---- */
#define CH32_TONE_TIMER 4
#define CH32_TONE_TIMER_BASE CH32_TIM4_BASE
#define CH32_TONE_TIMER_CLKEN_ADDR 0x4002101cu
#define CH32_TONE_TIMER_CLKEN_MASK 0x00000004u
#define CH32_TONE_TIMER_IRQ CH32_IRQN_TIM4
#define CH32_TONE_TIMER_HANDLER TIM4_IRQHandler
#define CH32_TONE_SHARES_PWM 0
/* CNT and ATRLR are 32 bit on this timer: a 16-bit store would be
 * replicated into both halves. See ch32_registers.h. */
#define CH32_TONE_TIMER_BITS 32

/* ---- Servo: TIM3, which is also a PWM timer here, so
 *      analogWrite() on PA6, PA7, PB0, PB1
 *      is disturbed while a servo is attached. ---- */
#define CH32_SERVO_TIMER 3
#define CH32_SERVO_TIMER_BASE CH32_TIM3_BASE
#define CH32_SERVO_TIMER_CLKEN_ADDR 0x4002101cu
#define CH32_SERVO_TIMER_CLKEN_MASK 0x00000002u
#define CH32_SERVO_TIMER_IRQ CH32_IRQN_TIM3
#define CH32_SERVO_TIMER_HANDLER TIM3_IRQHandler
#define CH32_SERVO_SHARES_PWM 1
#define CH32_SERVO_TIMER_BITS 16

/* Generic boards have no on-board LED. This placeholder only exists so
 * that the stock examples compile; it is the lowest-numbered pad present
 * on every part in the series. Override it per board or on the command
 * line: --build-property build.extra_flags=-DLED_BUILTIN=PC13 */
#ifndef LED_BUILTIN
#define LED_BUILTIN PA0
#endif
