/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: ch32-device-data tables @ git 0a1eed7b2e00066438a2ed25c2dce5aeca91bc18
 *
 * CH32V303 pin map: the union of all 5 part numbers in the
 * series, so the same header serves the ANY menu entry and every SKU.
 *
 * Pin numbers are port-encoded (ADR-0010): pin = (port << 5) | bit.
 * The valid set is SPARSE. NUM_DIGITAL_PINS is one past the highest pin
 * number, NOT a pad count, and 0..NUM_DIGITAL_PINS-1 is not a usable
 * loop range - test with digitalPinIsValid(pin).
 *
 * A pad missing from a given package is left unbonded: writing it only
 * touches a register bit with nothing attached, which is harmless.
 */
#pragma once

#include "ch32_pins.h"

#define CH32_VARIANT_CH32V303 1

/* ---- GPIO pads: 75 in the series, 31 of them on every part ---- */
#define PA0  CH32_PIN(0,  0)
#define PA1  CH32_PIN(0,  1)
#define PA2  CH32_PIN(0,  2)
#define PA3  CH32_PIN(0,  3)
#define PA4  CH32_PIN(0,  4)
#define PA6  CH32_PIN(0,  6)
#define PA7  CH32_PIN(0,  7)
#define PA8  CH32_PIN(0,  8)
#define PA9  CH32_PIN(0,  9)
#define PA10 CH32_PIN(0, 10)
#define PA11 CH32_PIN(0, 11)
#define PA12 CH32_PIN(0, 12)
#define PA13 CH32_PIN(0, 13)
#define PA14 CH32_PIN(0, 14)
#define PA15 CH32_PIN(0, 15)
#define PB0  CH32_PIN(1,  0)
#define PB1  CH32_PIN(1,  1)
#define PB2  CH32_PIN(1,  2)
#define PB3  CH32_PIN(1,  3)
#define PB4  CH32_PIN(1,  4)
#define PB5  CH32_PIN(1,  5)
#define PB6  CH32_PIN(1,  6)
#define PB7  CH32_PIN(1,  7)
#define PB8  CH32_PIN(1,  8)
#define PB9  CH32_PIN(1,  9)
#define PB10 CH32_PIN(1, 10)
#define PB11 CH32_PIN(1, 11)
#define PB12 CH32_PIN(1, 12)
#define PB13 CH32_PIN(1, 13)
#define PB14 CH32_PIN(1, 14)
#define PB15 CH32_PIN(1, 15)
#define PC0  CH32_PIN(2,  0)
#define PC1  CH32_PIN(2,  1)
#define PC2  CH32_PIN(2,  2)
#define PC3  CH32_PIN(2,  3)
#define PC4  CH32_PIN(2,  4)
#define PC5  CH32_PIN(2,  5)
#define PC6  CH32_PIN(2,  6)
#define PC7  CH32_PIN(2,  7)
#define PC8  CH32_PIN(2,  8)
#define PC10 CH32_PIN(2, 10)
#define PC11 CH32_PIN(2, 11)
#define PC12 CH32_PIN(2, 12)
#define PD0  CH32_PIN(3,  0)
#define PD1  CH32_PIN(3,  1)
#define PD2  CH32_PIN(3,  2)
#define PD3  CH32_PIN(3,  3)
#define PD4  CH32_PIN(3,  4)
#define PD5  CH32_PIN(3,  5)
#define PD6  CH32_PIN(3,  6)
#define PD7  CH32_PIN(3,  7)
#define PD8  CH32_PIN(3,  8)
#define PD9  CH32_PIN(3,  9)
#define PD10 CH32_PIN(3, 10)
#define PD11 CH32_PIN(3, 11)
#define PD12 CH32_PIN(3, 12)
#define PD13 CH32_PIN(3, 13)
#define PD14 CH32_PIN(3, 14)
#define PD15 CH32_PIN(3, 15)
#define PE0  CH32_PIN(4,  0)
#define PE1  CH32_PIN(4,  1)
#define PE2  CH32_PIN(4,  2)
#define PE3  CH32_PIN(4,  3)
#define PE4  CH32_PIN(4,  4)
#define PE5  CH32_PIN(4,  5)
#define PE6  CH32_PIN(4,  6)
#define PE7  CH32_PIN(4,  7)
#define PE8  CH32_PIN(4,  8)
#define PE9  CH32_PIN(4,  9)
#define PE10 CH32_PIN(4, 10)
#define PE11 CH32_PIN(4, 11)
#define PE12 CH32_PIN(4, 12)
#define PE13 CH32_PIN(4, 13)
#define PE14 CH32_PIN(4, 14)
#define PE15 CH32_PIN(4, 15)

/* Bit n set = P<port>n is bonded out on at least one part in the series. */
#define CH32_PORT_MASK_A 0x0000ffdfu
#define CH32_PORT_MASK_B 0x0000ffffu
#define CH32_PORT_MASK_C 0x00001dffu
#define CH32_PORT_MASK_D 0x0000ffffu
#define CH32_PORT_MASK_E 0x0000ffffu
#define CH32_PORT_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_MASK(port) ( \
    (port) == 0 ? CH32_PORT_MASK_A : \
    (port) == 1 ? CH32_PORT_MASK_B : \
    (port) == 2 ? CH32_PORT_MASK_C : \
    (port) == 3 ? CH32_PORT_MASK_D : \
    (port) == 4 ? CH32_PORT_MASK_E : \
    (port) == 5 ? CH32_PORT_MASK_F : \
    0u)

/* Bit n set = P<port>n is bonded out on EVERY part in the series,
 * i.e. the pins a sketch built for the ANY menu entry can rely on. */
#define CH32_PORT_COMMON_MASK_A 0x0000ffdfu
#define CH32_PORT_COMMON_MASK_B 0x0000ffffu
#define CH32_PORT_COMMON_MASK_C 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_D 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_E 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK(port) ( \
    (port) == 0 ? CH32_PORT_COMMON_MASK_A : \
    (port) == 1 ? CH32_PORT_COMMON_MASK_B : \
    (port) == 2 ? CH32_PORT_COMMON_MASK_C : \
    (port) == 3 ? CH32_PORT_COMMON_MASK_D : \
    (port) == 4 ? CH32_PORT_COMMON_MASK_E : \
    (port) == 5 ? CH32_PORT_COMMON_MASK_F : \
    0u)

#define NUM_DIGITAL_PINS 144   /* highest pin number + 1, not a pad count */
#define PINS_COUNT       NUM_DIGITAL_PINS
#define CH32_GPIO_COUNT  75   /* actual pads in the series */

/* ---- ADC1 analog inputs (15 channels) ---- */
/* Channels [5] are not bonded out in this series. */
#define NUM_ANALOG_INPUTS 16   /* highest channel + 1; see the gaps above */
#define A0   PA0
#define A1   PA1
#define A2   PA2
#define A3   PA3
#define A4   PA4
#define A6   PA6
#define A7   PA7
#define A8   PB0
#define A9   PB1
#define A10  PC0
#define A11  PC1
#define A12  PC2
#define A13  PC3
#define A14  PC4
#define A15  PC5
#define CH32_PIN_TO_ADC_CHANNEL(p) ( \
    (p) == PA0 ? 0 : \
    (p) == PA1 ? 1 : \
    (p) == PA2 ? 2 : \
    (p) == PA3 ? 3 : \
    (p) == PA4 ? 4 : \
    (p) == PA6 ? 6 : \
    (p) == PA7 ? 7 : \
    (p) == PB0 ? 8 : \
    (p) == PB1 ? 9 : \
    (p) == PC0 ? 10 : \
    (p) == PC1 ? 11 : \
    (p) == PC2 ? 12 : \
    (p) == PC3 ? 13 : \
    (p) == PC4 ? 14 : \
    (p) == PC5 ? 15 : \
    NOT_AN_ANALOG_PIN)
#define CH32_ADC_CHANNEL_TO_PIN(c) ( \
    (c) == 0 ? PA0 : \
    (c) == 1 ? PA1 : \
    (c) == 2 ? PA2 : \
    (c) == 3 ? PA3 : \
    (c) == 4 ? PA4 : \
    (c) == 6 ? PA6 : \
    (c) == 7 ? PA7 : \
    (c) == 8 ? PB0 : \
    (c) == 9 ? PB1 : \
    (c) == 10 ? PC0 : \
    (c) == 11 ? PC1 : \
    (c) == 12 ? PC2 : \
    (c) == 13 ? PC3 : \
    (c) == 14 ? PC4 : \
    (c) == 15 ? PC5 : \
    NOT_A_PIN)

/* ---- USART pins (device-data; one route per USART, chosen for
 *      the whole series - see choose_uarts in generate.py) ---- */
/* USART1: route default, on every part */
#define CH32_SERIAL1_TX PA9
#define CH32_SERIAL1_RX PA10
#define CH32_SERIAL1_HANDLER USART1_IRQHandler
#define CH32_SERIAL1_IRQ CH32_IRQN_USART1
#define CH32_SERIAL1_REMAP_MASK 0x00000004u
#define CH32_SERIAL1_REMAP_VAL  0x00000000u
#define CH32_SERIAL1_REMAP2_MASK 0x04000000u
#define CH32_SERIAL1_REMAP2_VAL  0x00000000u
/* SERIAL1 routes for setRoute()/setPins(): route number, then TX, RX */
#define CH32_SERIAL1_ROUTE_COUNT 2
#define CH32_SERIAL1_ROUTES { \
    { 0, { PA9, PA10, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00000000u }, \
    { 1, { PB6, PB7, CH32_ROUTE_NO_PIN }, 0x00000004u, 0x00000000u }, \
}
/* USART2: route default, on every part */
#define CH32_SERIAL2_TX PA2
#define CH32_SERIAL2_RX PA3
#define CH32_SERIAL2_HANDLER USART2_IRQHandler
#define CH32_SERIAL2_IRQ CH32_IRQN_USART2
#define CH32_SERIAL2_REMAP_MASK 0x00000008u
#define CH32_SERIAL2_REMAP_VAL  0x00000000u
/* SERIAL2 routes for setRoute()/setPins(): route number, then TX, RX */
#define CH32_SERIAL2_ROUTE_COUNT 2
#define CH32_SERIAL2_ROUTES { \
    { 0, { PA2, PA3, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00000000u }, \
    { 1, { PD5, PD6, CH32_ROUTE_NO_PIN }, 0x00000008u, 0x00000000u }, \
}
/* USART3: route default, on every part */
#define CH32_SERIAL3_TX PB10
#define CH32_SERIAL3_RX PB11
#define CH32_SERIAL3_HANDLER USART3_IRQHandler
#define CH32_SERIAL3_IRQ CH32_IRQN_USART3
#define CH32_SERIAL3_REMAP_MASK 0x00000030u
#define CH32_SERIAL3_REMAP_VAL  0x00000000u
/* SERIAL3 routes for setRoute()/setPins(): route number, then TX, RX */
#define CH32_SERIAL3_ROUTE_COUNT 2
#define CH32_SERIAL3_ROUTES { \
    { 0, { PB10, PB11, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00000000u }, \
    { 1, { PC10, PC11, CH32_ROUTE_NO_PIN }, 0x00000010u, 0x00000000u }, \
}
/* USART4: route default, on 4 of 5 parts */
#define CH32_SERIAL4_TX PC10
#define CH32_SERIAL4_RX PC11
#define CH32_SERIAL4_HANDLER UART4_IRQHandler
#define CH32_SERIAL4_IRQ CH32_IRQN_UART4
#define CH32_SERIAL4_REMAP2_MASK 0x00030000u
#define CH32_SERIAL4_REMAP2_VAL  0x00000000u
/* SERIAL4 routes for setRoute()/setPins(): route number, then TX, RX */
#define CH32_SERIAL4_ROUTE_COUNT 2
#define CH32_SERIAL4_ROUTES { \
    { 0, { PC10, PC11, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00000000u }, \
    { 1, { PB0, PB1, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00010000u }, \
}
/* USART5: route default, on 4 of 5 parts */
#define CH32_SERIAL5_TX PC12
#define CH32_SERIAL5_RX PD2
#define CH32_SERIAL5_HANDLER UART5_IRQHandler
#define CH32_SERIAL5_IRQ CH32_IRQN_UART5
#define CH32_SERIAL5_REMAP2_MASK 0x000c0000u
#define CH32_SERIAL5_REMAP2_VAL  0x00000000u
/* SERIAL5 routes for setRoute()/setPins(): route number, then TX, RX */
#define CH32_SERIAL5_ROUTE_COUNT 2
#define CH32_SERIAL5_ROUTES { \
    { 0, { PC12, PD2, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00000000u }, \
    { 1, { PB4, PB5, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00040000u }, \
}
#ifndef CH32_SERIAL_DEFAULT
#define CH32_SERIAL_DEFAULT 1
#endif

/* ---- I2C pins (device-data; one route per instance,
 *      chosen for the whole series - see choose_i2cs) ---- */
/* I2C1: route default, on every part */
#define CH32_I2C1_SCL PB6
#define CH32_I2C1_SDA PB7
#define CH32_I2C1_REMAP_MASK 0x00000002u
#define CH32_I2C1_REMAP_VAL  0x00000000u
/* I2C1 routes for setRoute()/setPins(): route number, then SCL, SDA */
#define CH32_I2C1_ROUTE_COUNT 2
#define CH32_I2C1_ROUTES { \
    { 0, { PB6, PB7, CH32_ROUTE_NO_PIN }, 0x00000000u, 0x00000000u }, \
    { 1, { PB8, PB9, CH32_ROUTE_NO_PIN }, 0x00000002u, 0x00000000u }, \
}
/* I2C2: route default, on every part */
#define CH32_I2C2_SCL PB10
#define CH32_I2C2_SDA PB11
/* Arduino's standard names for the first bus (Wire). */
#ifndef PIN_WIRE_SCL
#define PIN_WIRE_SCL CH32_I2C1_SCL
#define PIN_WIRE_SDA CH32_I2C1_SDA
#define SCL PIN_WIRE_SCL
#define SDA PIN_WIRE_SDA
#endif

/* ---- SPI pins (device-data; one route per instance,
 *      chosen for the whole series - see choose_spis).
 *      NSS is not listed: Arduino drives chip select as a GPIO. ---- */
/* SPI1: route remap-1, on every part */
#define CH32_SPI1_SCK PB3
#define CH32_SPI1_MISO PB4
#define CH32_SPI1_MOSI PB5
#define CH32_SPI1_REMAP_MASK 0x00000001u
#define CH32_SPI1_REMAP_VAL  0x00000001u
/* SPI1 routes for setRoute()/setPins(): route number, then SCK, MISO, MOSI */
#define CH32_SPI1_ROUTE_COUNT 1
#define CH32_SPI1_ROUTES { \
    { 1, { PB3, PB4, PB5 }, 0x00000001u, 0x00000000u }, \
}
/* SPI2: route default, on every part */
#define CH32_SPI2_SCK PB13
#define CH32_SPI2_MISO PB14
#define CH32_SPI2_MOSI PB15
/* SPI3: route default, on every part */
#define CH32_SPI3_SCK PB3
#define CH32_SPI3_MISO PB4
#define CH32_SPI3_MOSI PB5
#define CH32_SPI3_REMAP_MASK 0x10000000u
#define CH32_SPI3_REMAP_VAL  0x00000000u
/* SPI3 routes for setRoute()/setPins(): route number, then SCK, MISO, MOSI */
#define CH32_SPI3_ROUTE_COUNT 2
#define CH32_SPI3_ROUTES { \
    { 0, { PB3, PB4, PB5 }, 0x00000000u, 0x00000000u }, \
    { 1, { PC10, PC11, PC12 }, 0x10000000u, 0x00000000u }, \
}
/* Arduino's standard names for the first bus (SPI). */
#ifndef PIN_SPI_SCK
#define PIN_SPI_SCK CH32_SPI1_SCK
#define PIN_SPI_MISO CH32_SPI1_MISO
#define PIN_SPI_MOSI CH32_SPI1_MOSI
#define SCK PIN_SPI_SCK
#define MISO PIN_SPI_MISO
#define MOSI PIN_SPI_MOSI
#define PIN_SPI_SS PA15
#define SS PIN_SPI_SS
#endif

/* ---- PWM: 12 pads on TIM1/TIM2/TIM3, default route ---- */
#define CH32_PWM_PIN_COUNT 12
#define CH32_PWM_PIN_TO_TIMER(p) ( \
    (p) == PA8 ? 1 : \
    (p) == PA9 ? 1 : \
    (p) == PA10 ? 1 : \
    (p) == PA11 ? 1 : \
    (p) == PA0 ? 2 : \
    (p) == PA1 ? 2 : \
    (p) == PA2 ? 2 : \
    (p) == PA3 ? 2 : \
    (p) == PA6 ? 3 : \
    (p) == PA7 ? 3 : \
    (p) == PB0 ? 3 : \
    (p) == PB1 ? 3 : \
    0)
#define CH32_PWM_PIN_TO_CHANNEL(p) ( \
    (p) == PA8 ? 1 : \
    (p) == PA9 ? 2 : \
    (p) == PA10 ? 3 : \
    (p) == PA11 ? 4 : \
    (p) == PA0 ? 1 : \
    (p) == PA1 ? 2 : \
    (p) == PA2 ? 3 : \
    (p) == PA3 ? 4 : \
    (p) == PA6 ? 1 : \
    (p) == PA7 ? 2 : \
    (p) == PB0 ? 3 : \
    (p) == PB1 ? 4 : \
    0)

/* ---- DAC: analogWrite() drives the converter on these pads,
 *      not a timer. ---- */
/* DAC1: on every part */
#define CH32_DAC1_PIN PA4

/* ---- tone(): TIM7, free of PWM pads. ---- */
#define CH32_TONE_TIMER 7
#define CH32_TONE_TIMER_BASE CH32_TIM7_BASE
#define CH32_TONE_TIMER_RCC CH32_RCC_APB1_TIM7
#define CH32_TONE_TIMER_ON_APB2 0
#define CH32_TONE_TIMER_IRQ CH32_IRQN_TIM7
#define CH32_TONE_TIMER_HANDLER TIM7_IRQHandler
#define CH32_TONE_SHARES_PWM 0

/* ---- Servo: TIM6, free of PWM pads. ---- */
#define CH32_SERVO_TIMER 6
#define CH32_SERVO_TIMER_BASE CH32_TIM6_BASE
#define CH32_SERVO_TIMER_RCC CH32_RCC_APB1_TIM6
#define CH32_SERVO_TIMER_ON_APB2 0
#define CH32_SERVO_TIMER_IRQ CH32_IRQN_TIM6
#define CH32_SERVO_TIMER_HANDLER TIM6_IRQHandler
#define CH32_SERVO_SHARES_PWM 0

/* Generic boards have no on-board LED. This placeholder only exists so
 * that the stock examples compile; it is the lowest-numbered pad present
 * on every part in the series. Override it per board or on the command
 * line: --build-property build.extra_flags=-DLED_BUILTIN=PC13 */
#ifndef LED_BUILTIN
#define LED_BUILTIN PA0
#endif
