/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: ch32-device-data tables @ git 66a421f41207c1110188e1dc0ecced98fa026026
 *
 * CH32X035 pin map: the union of all 7 part numbers in the
 * series, so the same header serves the ANY menu entry and every SKU.
 *
 * Pin numbers are port-encoded (ADR-0010): pin = (port << 5) | bit.
 * The valid set is SPARSE. NUM_DIGITAL_PINS is one past the highest pin
 * number, NOT a pad count, and 0..NUM_DIGITAL_PINS-1 is not a usable
 * loop range - test with digitalPinIsValid(pin).
 *
 * A pad missing from a given package is left unbonded: writing it only
 * touches a register bit with nothing attached, which is harmless.
 *
 * Exception, errata x035-pc10-pc17-bonded: PC10/PC11 have no pin of their
 * own but are internally bonded to PC17/PC16, so writing them drives a
 * real pin.
 */
#pragma once

#include "ch32_pins.h"

#define CH32_VARIANT_CH32X035 1

/* ---- GPIO pads: 60 in the series, 11 of them on every part ---- */
#define PA0  CH32_PIN(0,  0)
#define PA1  CH32_PIN(0,  1)
#define PA2  CH32_PIN(0,  2)
#define PA3  CH32_PIN(0,  3)
#define PA4  CH32_PIN(0,  4)
#define PA5  CH32_PIN(0,  5)
#define PA6  CH32_PIN(0,  6)
#define PA7  CH32_PIN(0,  7)
#define PA8  CH32_PIN(0,  8)
#define PA9  CH32_PIN(0,  9)
#define PA10 CH32_PIN(0, 10)
#define PA11 CH32_PIN(0, 11)
#define PA12 CH32_PIN(0, 12)
#define PA13 CH32_PIN(0, 13)
#define PA14 CH32_PIN(0, 14)
#define PA15 CH32_PIN(0, 15)
#define PA16 CH32_PIN(0, 16)
#define PA17 CH32_PIN(0, 17)
#define PA18 CH32_PIN(0, 18)
#define PA19 CH32_PIN(0, 19)
#define PA20 CH32_PIN(0, 20)
#define PA21 CH32_PIN(0, 21)
#define PA22 CH32_PIN(0, 22)
#define PA23 CH32_PIN(0, 23)
#define PB0  CH32_PIN(1,  0)
#define PB1  CH32_PIN(1,  1)
#define PB2  CH32_PIN(1,  2)
#define PB3  CH32_PIN(1,  3)
#define PB4  CH32_PIN(1,  4)
#define PB5  CH32_PIN(1,  5)
#define PB6  CH32_PIN(1,  6)
#define PB7  CH32_PIN(1,  7)
#define PB8  CH32_PIN(1,  8)
#define PB9  CH32_PIN(1,  9)
#define PB10 CH32_PIN(1, 10)
#define PB11 CH32_PIN(1, 11)
#define PB12 CH32_PIN(1, 12)
#define PB13 CH32_PIN(1, 13)
#define PB14 CH32_PIN(1, 14)
#define PB15 CH32_PIN(1, 15)
#define PB16 CH32_PIN(1, 16)
#define PB17 CH32_PIN(1, 17)
#define PB18 CH32_PIN(1, 18)
#define PB19 CH32_PIN(1, 19)
#define PB20 CH32_PIN(1, 20)
#define PB21 CH32_PIN(1, 21)
#define PC0  CH32_PIN(2,  0)
#define PC1  CH32_PIN(2,  1)
#define PC2  CH32_PIN(2,  2)
#define PC3  CH32_PIN(2,  3)
#define PC4  CH32_PIN(2,  4)
#define PC5  CH32_PIN(2,  5)
#define PC6  CH32_PIN(2,  6)
#define PC7  CH32_PIN(2,  7)
#define PC14 CH32_PIN(2, 14)
#define PC15 CH32_PIN(2, 15)
#define PC16 CH32_PIN(2, 16)
#define PC17 CH32_PIN(2, 17)
#define PC18 CH32_PIN(2, 18)
#define PC19 CH32_PIN(2, 19)

/* Bit n set = P<port>n is bonded out on at least one part in the series. */
#define CH32_PORT_MASK_A 0x00ffffffu
#define CH32_PORT_MASK_B 0x003fffffu
#define CH32_PORT_MASK_C 0x000fc0ffu
#define CH32_PORT_MASK_D 0x00000000u   /* port absent */
#define CH32_PORT_MASK_E 0x00000000u   /* port absent */
#define CH32_PORT_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_MASK(port) ( \
    (port) == 0 ? CH32_PORT_MASK_A : \
    (port) == 1 ? CH32_PORT_MASK_B : \
    (port) == 2 ? CH32_PORT_MASK_C : \
    (port) == 3 ? CH32_PORT_MASK_D : \
    (port) == 4 ? CH32_PORT_MASK_E : \
    (port) == 5 ? CH32_PORT_MASK_F : \
    0u)

/* Bit n set = P<port>n is bonded out on EVERY part in the series,
 * i.e. the pins a sketch built for the ANY menu entry can rely on. */
#define CH32_PORT_COMMON_MASK_A 0x000000ecu
#define CH32_PORT_COMMON_MASK_B 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_C 0x000fc000u
#define CH32_PORT_COMMON_MASK_D 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_E 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK(port) ( \
    (port) == 0 ? CH32_PORT_COMMON_MASK_A : \
    (port) == 1 ? CH32_PORT_COMMON_MASK_B : \
    (port) == 2 ? CH32_PORT_COMMON_MASK_C : \
    (port) == 3 ? CH32_PORT_COMMON_MASK_D : \
    (port) == 4 ? CH32_PORT_COMMON_MASK_E : \
    (port) == 5 ? CH32_PORT_COMMON_MASK_F : \
    0u)

/* Register bits that must never be driven; see the errata note above. */
#define CH32_UNUSABLE_PIN_COUNT 2
#define CH32_UNUSABLE_PINS { \
    CH32_PIN(2, 10) /* PC10, x035-pc10-pc17-bonded */, \
    CH32_PIN(2, 11) /* PC11, x035-pc10-pc17-bonded */, \
    }

#define NUM_DIGITAL_PINS 84   /* highest pin number + 1, not a pad count */
#define PINS_COUNT       NUM_DIGITAL_PINS
#define CH32_GPIO_COUNT  60   /* actual pads in the series */

/* ---- ADC1 analog inputs (14 channels) ---- */
#define NUM_ANALOG_INPUTS 14
#define A0   PA0
#define A1   PA1
#define A2   PA2
#define A3   PA3
#define A4   PA4
#define A5   PA5
#define A6   PA6
#define A7   PA7
#define A8   PB0
#define A9   PB1
#define A10  PC0
#define A11  PC1
#define A12  PC2
#define A13  PC3
#define CH32_PIN_TO_ADC_CHANNEL(p) ( \
    (p) == PA0 ? 0 : \
    (p) == PA1 ? 1 : \
    (p) == PA2 ? 2 : \
    (p) == PA3 ? 3 : \
    (p) == PA4 ? 4 : \
    (p) == PA5 ? 5 : \
    (p) == PA6 ? 6 : \
    (p) == PA7 ? 7 : \
    (p) == PB0 ? 8 : \
    (p) == PB1 ? 9 : \
    (p) == PC0 ? 10 : \
    (p) == PC1 ? 11 : \
    (p) == PC2 ? 12 : \
    (p) == PC3 ? 13 : \
    NOT_AN_ANALOG_PIN)
#define CH32_ADC_CHANNEL_TO_PIN(c) ( \
    (c) == 0 ? PA0 : \
    (c) == 1 ? PA1 : \
    (c) == 2 ? PA2 : \
    (c) == 3 ? PA3 : \
    (c) == 4 ? PA4 : \
    (c) == 5 ? PA5 : \
    (c) == 6 ? PA6 : \
    (c) == 7 ? PA7 : \
    (c) == 8 ? PB0 : \
    (c) == 9 ? PB1 : \
    (c) == 10 ? PC0 : \
    (c) == 11 ? PC1 : \
    (c) == 12 ? PC2 : \
    (c) == 13 ? PC3 : \
    NOT_A_PIN)

/* ---- USART pins (device-data; one route per USART, chosen for
 *      the whole series - see choose_uarts in generate.py) ---- */
/* USART1: route default, on 4 of 7 parts */
#define CH32_SERIAL1_TX PB10
#define CH32_SERIAL1_RX PB11
#define CH32_SERIAL1_HANDLER USART1_IRQHandler
#define CH32_SERIAL1_IRQ CH32_IRQN_USART1
#define CH32_SERIAL1_REMAP_MASK 0x00000060u
#define CH32_SERIAL1_REMAP_VAL  0x00000000u
/* USART2: route default, on every part */
#define CH32_SERIAL2_TX PA2
#define CH32_SERIAL2_RX PA3
#define CH32_SERIAL2_HANDLER USART2_IRQHandler
#define CH32_SERIAL2_IRQ CH32_IRQN_USART2
#define CH32_SERIAL2_REMAP_MASK 0x00000380u
#define CH32_SERIAL2_REMAP_VAL  0x00000000u
/* USART3: route default, on 4 of 7 parts */
#define CH32_SERIAL3_TX PB3
#define CH32_SERIAL3_RX PB4
#define CH32_SERIAL3_HANDLER USART3_IRQHandler
#define CH32_SERIAL3_IRQ CH32_IRQN_USART3
#define CH32_SERIAL3_REMAP_MASK 0x00000c00u
#define CH32_SERIAL3_REMAP_VAL  0x00000000u
/* USART4: route default, on 5 of 7 parts */
#define CH32_SERIAL4_TX PB0
#define CH32_SERIAL4_RX PB1
#define CH32_SERIAL4_HANDLER USART4_IRQHandler
#define CH32_SERIAL4_IRQ CH32_IRQN_USART4
#define CH32_SERIAL4_REMAP_MASK 0x00007000u
#define CH32_SERIAL4_REMAP_VAL  0x00000000u
#ifndef CH32_SERIAL_DEFAULT
#define CH32_SERIAL_DEFAULT 1
#endif

/* ---- PWM: 10 pads on TIM1/TIM2/TIM3, default route ---- */
#define CH32_PWM_PIN_COUNT 10
#define CH32_PWM_PIN_TO_TIMER(p) ( \
    (p) == PB9 ? 1 : \
    (p) == PB10 ? 1 : \
    (p) == PB11 ? 1 : \
    (p) == PC16 ? 1 : \
    (p) == PA0 ? 2 : \
    (p) == PA1 ? 2 : \
    (p) == PA2 ? 2 : \
    (p) == PA3 ? 2 : \
    (p) == PA6 ? 3 : \
    (p) == PA7 ? 3 : \
    0)
#define CH32_PWM_PIN_TO_CHANNEL(p) ( \
    (p) == PB9 ? 1 : \
    (p) == PB10 ? 2 : \
    (p) == PB11 ? 3 : \
    (p) == PC16 ? 4 : \
    (p) == PA0 ? 1 : \
    (p) == PA1 ? 2 : \
    (p) == PA2 ? 3 : \
    (p) == PA3 ? 4 : \
    (p) == PA6 ? 1 : \
    (p) == PA7 ? 2 : \
    0)

/* Generic boards have no on-board LED. This placeholder only exists so
 * that the stock examples compile; it is the lowest-numbered pad present
 * on every part in the series. Override it per board or on the command
 * line: --build-property build.extra_flags=-DLED_BUILTIN=PC13 */
#ifndef LED_BUILTIN
#define LED_BUILTIN PA2
#endif
