/* DO NOT EDIT - machine generated by tools/generate/generate.py
 * source: ch32-device-data tables @ git 8c09ab446f510a1ab056dad4c7f3ae5fbdc91ad9
 *
 * CH32M030 pin map: the union of all 5 part numbers in the
 * series, so the same header serves the ANY menu entry and every SKU.
 *
 * Pin numbers are port-encoded (ADR-0010): pin = (port << 5) | bit.
 * The valid set is SPARSE. NUM_DIGITAL_PINS is one past the highest pin
 * number, NOT a pad count, and 0..NUM_DIGITAL_PINS-1 is not a usable
 * loop range - test with digitalPinIsValid(pin).
 *
 * A pad missing from a given package is left unbonded: writing it only
 * touches a register bit with nothing attached, which is harmless.
 */
#pragma once

#include "ch32_pins.h"

#define CH32_VARIANT_CH32M030 1

/* ---- GPIO pads: 37 in the series, 16 of them on every part ---- */
#define PA0  CH32_PIN(0,  0)
#define PA1  CH32_PIN(0,  1)
#define PA2  CH32_PIN(0,  2)
#define PA3  CH32_PIN(0,  3)
#define PA4  CH32_PIN(0,  4)
#define PA5  CH32_PIN(0,  5)
#define PA6  CH32_PIN(0,  6)
#define PA7  CH32_PIN(0,  7)
#define PA8  CH32_PIN(0,  8)
#define PA10 CH32_PIN(0, 10)
#define PA11 CH32_PIN(0, 11)
#define PA12 CH32_PIN(0, 12)
#define PA13 CH32_PIN(0, 13)
#define PA14 CH32_PIN(0, 14)
#define PA15 CH32_PIN(0, 15)
#define PB0  CH32_PIN(1,  0)
#define PB1  CH32_PIN(1,  1)
#define PB2  CH32_PIN(1,  2)
#define PB3  CH32_PIN(1,  3)
#define PB4  CH32_PIN(1,  4)
#define PB5  CH32_PIN(1,  5)
#define PB6  CH32_PIN(1,  6)
#define PB7  CH32_PIN(1,  7)
#define PB8  CH32_PIN(1,  8)
#define PB9  CH32_PIN(1,  9)
#define PB10 CH32_PIN(1, 10)
#define PB11 CH32_PIN(1, 11)
#define PB12 CH32_PIN(1, 12)
#define PB13 CH32_PIN(1, 13)
#define PB14 CH32_PIN(1, 14)
#define PB15 CH32_PIN(1, 15)
#define PC0  CH32_PIN(2,  0)
#define PC1  CH32_PIN(2,  1)
#define PC2  CH32_PIN(2,  2)
#define PC3  CH32_PIN(2,  3)
#define PC4  CH32_PIN(2,  4)
#define PC5  CH32_PIN(2,  5)

/* Bit n set = P<port>n is bonded out on at least one part in the series. */
#define CH32_PORT_MASK_A 0x0000fdffu
#define CH32_PORT_MASK_B 0x0000ffffu
#define CH32_PORT_MASK_C 0x0000003fu
#define CH32_PORT_MASK_D 0x00000000u   /* port absent */
#define CH32_PORT_MASK_E 0x00000000u   /* port absent */
#define CH32_PORT_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_MASK(port) ( \
    (port) == 0 ? CH32_PORT_MASK_A : \
    (port) == 1 ? CH32_PORT_MASK_B : \
    (port) == 2 ? CH32_PORT_MASK_C : \
    (port) == 3 ? CH32_PORT_MASK_D : \
    (port) == 4 ? CH32_PORT_MASK_E : \
    (port) == 5 ? CH32_PORT_MASK_F : \
    0u)

/* Bit n set = P<port>n is bonded out on EVERY part in the series,
 * i.e. the pins a sketch built for the ANY menu entry can rely on. */
#define CH32_PORT_COMMON_MASK_A 0x0000258cu
#define CH32_PORT_COMMON_MASK_B 0x00002f73u
#define CH32_PORT_COMMON_MASK_C 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_D 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_E 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK_F 0x00000000u   /* port absent */
#define CH32_PORT_COMMON_MASK(port) ( \
    (port) == 0 ? CH32_PORT_COMMON_MASK_A : \
    (port) == 1 ? CH32_PORT_COMMON_MASK_B : \
    (port) == 2 ? CH32_PORT_COMMON_MASK_C : \
    (port) == 3 ? CH32_PORT_COMMON_MASK_D : \
    (port) == 4 ? CH32_PORT_COMMON_MASK_E : \
    (port) == 5 ? CH32_PORT_COMMON_MASK_F : \
    0u)

#define NUM_DIGITAL_PINS 70   /* highest pin number + 1, not a pad count */
#define PINS_COUNT       NUM_DIGITAL_PINS
#define CH32_GPIO_COUNT  37   /* actual pads in the series */

/* ---- ADC1 analog inputs (20 channels) ---- */
#define NUM_ANALOG_INPUTS 20
#define A0   PB2
#define A1   PB3
#define A2   PA7
#define A3   PB5
#define A4   PB6
#define A5   PA4
#define A6   PA5
#define A7   PA8
#define A8   PA11
#define A9   PA14
#define A10  PA15
#define A11  PB0
#define A12  PB1
#define A13  PA0
#define A14  PA1
#define A15  PA2
#define A16  PA3
#define A17  PB4
#define A18  PA13
#define A19  PA12
#define CH32_PIN_TO_ADC_CHANNEL(p) ( \
    (p) == PB2 ? 0 : \
    (p) == PB3 ? 1 : \
    (p) == PA7 ? 2 : \
    (p) == PB5 ? 3 : \
    (p) == PB6 ? 4 : \
    (p) == PA4 ? 5 : \
    (p) == PA5 ? 6 : \
    (p) == PA8 ? 7 : \
    (p) == PA11 ? 8 : \
    (p) == PA14 ? 9 : \
    (p) == PA15 ? 10 : \
    (p) == PB0 ? 11 : \
    (p) == PB1 ? 12 : \
    (p) == PA0 ? 13 : \
    (p) == PA1 ? 14 : \
    (p) == PA2 ? 15 : \
    (p) == PA3 ? 16 : \
    (p) == PB4 ? 17 : \
    (p) == PA13 ? 18 : \
    (p) == PA12 ? 19 : \
    NOT_AN_ANALOG_PIN)
#define CH32_ADC_CHANNEL_TO_PIN(c) ( \
    (c) == 0 ? PB2 : \
    (c) == 1 ? PB3 : \
    (c) == 2 ? PA7 : \
    (c) == 3 ? PB5 : \
    (c) == 4 ? PB6 : \
    (c) == 5 ? PA4 : \
    (c) == 6 ? PA5 : \
    (c) == 7 ? PA8 : \
    (c) == 8 ? PA11 : \
    (c) == 9 ? PA14 : \
    (c) == 10 ? PA15 : \
    (c) == 11 ? PB0 : \
    (c) == 12 ? PB1 : \
    (c) == 13 ? PA0 : \
    (c) == 14 ? PA1 : \
    (c) == 15 ? PA2 : \
    (c) == 16 ? PA3 : \
    (c) == 17 ? PB4 : \
    (c) == 18 ? PA13 : \
    (c) == 19 ? PA12 : \
    NOT_A_PIN)

/* ---- USART pins (device-data; one route per USART, chosen for
 *      the whole series - see choose_uarts in generate.py) ---- */
/* USART1: route default, on 3 of 5 parts */
#define CH32_SERIAL1_TX PC1
#define CH32_SERIAL1_RX PC0
#define CH32_SERIAL1_HANDLER USART1_IRQHandler
#define CH32_SERIAL1_IRQ CH32_IRQN_USART1
#define CH32_SERIAL_DEFAULT 1

/* Generic boards have no on-board LED. This placeholder only exists so
 * that the stock examples compile; it is the lowest-numbered pad present
 * on every part in the series. Override it per board or on the command
 * line: --build-property build.extra_flags=-DLED_BUILTIN=PC13 */
#ifndef LED_BUILTIN
#define LED_BUILTIN PA2
#endif
