"""docs/peripheral-support.ja.md does not claim a peripheral the silicon lacks.

The table is generated by hand, from the EVT example trees, which are not in
CI - so nothing checked it. Its marks answer "does WCH ship an example for
this?", which is deliberately *not* the same question as "does this silicon
have it": the document says so itself, and warns that a blank may only mean
that EVT has no example.

That asymmetry is why this checks one direction only.

  O with no clock enable anywhere in the group  ->  a claim the device tables
                                                    contradict. Asserted.
  blank where a clock enable exists             ->  the documented "EVT has no
                                                    example" case. Ignored.

The second source is CH32_CLKEN_<X>_ADDR in the generated variant headers,
which comes from ch32-device-data's clock_enables.csv. It is in the repository,
so this runs in CI where peripheral_matrix.py cannot.
"""
import pathlib
import re
import sys

import pytest

REPO = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "tests"))
sys.path.insert(0, str(REPO / "tools" / "generate"))

from sketch_requirements import series_capabilities   # noqa: E402

DOC = REPO / "docs" / "peripheral-support.ja.md"

# The bridge between two vocabularies, and the only thing written down here.
# Deliberately partial: a row earns an entry only when it is a clock-gated
# block with a clock enable of its own. GPIO, EXTI, PFIC, SysTick and RCC have
# no CH32_CLKEN_ row to check them against, and a row absent from here is
# simply not checked rather than assumed missing.
CLOCK_GATED = {
    "I2C": ("I2C1",),
    "SPI": ("SPI1",),
    "ADC": ("ADC1",),
    "DAC": ("DAC",),
    "USART": ("USART1",),
    "CAN": ("CAN1",),
    "Ethernet": ("ETH_MAC",),
    "SDIO": ("SDIO",),
    "DVP": ("DVP",),
    "RNG": ("RNG",),
    "LPTIM": ("LPTIM",),
    "I3C": ("I3C",),
    "FSMC": ("FSMC",),
    "QSPI": ("QSPI1",),
    "PSRAM": ("PSRAM",),
    "LTDC": ("LTDC",),
    # The USB rows. CH32V103 calls its device controller USB where the rest
    # call it USBFS, so the FS row accepts either.
    "USB": ("USBFS", "USB"),
    "USB HS": ("USBHS", "USBHS1"),
    "USB PD": ("USBPD", "USBPD0"),
    "USB SS": ("USBSS",),
}


# Disagreements between the two sources that are real and unresolved. Deleting
# the row from CLOCK_GATED would hide them; failing would make CI permanently
# red. Each entry is asserted to *still* disagree, so it cannot quietly rot
# once one side is fixed.
KNOWN_DISAGREEMENTS = {
    ("Ethernet", "V203/V208"):
        "EVT ships an ETH example under CH32V20x, but ch32-device-data's "
        "clock_enables.csv has no ETH row for that family - only for the "
        "CH32V307, CH32V407 and CH32H417 ones. WCH documents 10M Ethernet on "
        "CH32V208, so the gap is probably upstream's, but which side is wrong "
        "has to be settled against the reference manual. docs/todo.ja.md.",
}


def _group_to_series() -> dict:
    """Column heading -> the series under it, composed, never transcribed.

    generate.py knows series -> EVT family; peripheral_matrix.py knows EVT
    family -> the heading it prints. Writing the composition out again here
    would be a third copy to keep in step.
    """
    from generate import SERIES_CONFIG
    from peripheral_matrix import EVT_FAMILY

    heading = dict(EVT_FAMILY)
    out: dict = {}
    for series, cfg in SERIES_CONFIG.items():
        label = heading.get(cfg["family"])
        if label:
            out.setdefault(label, []).append(series)
    return out


def _rows():
    """(row label, {column: cell}) for every peripheral row in the document."""
    header = None
    for line in DOC.read_text(encoding="utf-8").splitlines():
        if line.startswith("| ペリフェラル |"):
            header = [c.strip() for c in line.strip("|").split("|")]
            continue
        if not header or not line.startswith("|") or set(line) <= set("|- "):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) != len(header):
            continue
        label = re.sub(r"\s*\(.*", "", cells[0]).strip()
        yield label, dict(zip(header, cells))


def test_the_document_still_parses():
    """A heading rename would make every assertion below vacuously true."""
    labels = {label for label, _ in _rows()}
    assert labels, f"no peripheral rows parsed out of {DOC.name}"
    missing = set(CLOCK_GATED) - labels
    assert not missing, (
        f"{DOC.name} no longer has rows for {sorted(missing)}; the table was "
        f"renamed and this check stopped looking at them")


def test_group_headings_resolve_to_series():
    groups = _group_to_series()
    assert groups, "SERIES_CONFIG and EVT_FAMILY did not compose"
    columns = {c for _, cells in _rows() for c in cells}
    unresolved = [g for g in groups if g not in columns]
    assert not unresolved, (
        f"peripheral_matrix.EVT_FAMILY prints headings the document does not "
        f"have: {unresolved}")


@pytest.mark.parametrize("label", sorted(CLOCK_GATED))
def test_a_mark_is_backed_by_a_clock_enable(label):
    caps = series_capabilities()
    groups = _group_to_series()
    tokens = CLOCK_GATED[label]
    wrong = []
    for row_label, cells in _rows():
        if row_label != label:
            continue
        for column, mark in cells.items():
            if column not in groups or mark != "○":
                continue
            if (label, column) in KNOWN_DISAGREEMENTS:
                continue
            if not any(token in caps.get(series, ())
                       for series in groups[column] for token in tokens):
                wrong.append(
                    f"{label} is marked O for {column}, but none of "
                    f"{groups[column]} declares a clock enable for "
                    f"{'/'.join(tokens)}")
    assert not wrong, "\n".join(wrong)


@pytest.mark.parametrize("key", sorted(KNOWN_DISAGREEMENTS))
def test_known_disagreements_still_disagree(key):
    """Remove the entry when the two sources agree again.

    A waiver nobody revisits is how a fixed problem stays recorded as broken.
    """
    label, column = key
    caps = series_capabilities()
    groups = _group_to_series()
    tokens = CLOCK_GATED[label]
    marked = any(cells.get(column) == "○"
                 for row_label, cells in _rows() if row_label == label)
    backed = any(token in caps.get(series, ())
                 for series in groups[column] for token in tokens)
    assert marked and not backed, (
        f"{label}/{column} no longer disagrees; drop it from "
        f"KNOWN_DISAGREEMENTS.\n{KNOWN_DISAGREEMENTS[key]}")
